### ISSUE TITLE
Multi tool not showing up

### ISSUE THREAD

**Issue by KennyB2** [Courseplay/Courseplay_FS25#100]
### Version

8.0.0.1

### SP/MP

SP (Singleplayer)

### What is your question about?

Course creation

### What is your question?

I just downloaded Courseplay 8.0.0.1 and i don't have the multiple tools bar to show up so i can have more then 1 combine going at a time. I tried 8.0.0.0 as well and still didn't get the Multiple Tools bar to show up in the basic settings part. I watched some youtube videos and in the videos they have the Multiple Tools bar in the basic settings. So I'm just wondering if i did something wrong or if its a bug for me. I attached a screen shot as evidence of the missing Multiple Tool setting.

Thanks

### Screenshots

![20241225001156_1](https://github.com/user-attachments/assets/07163bee-1591-481e-9090-cc6afbb22b98)

**Comment by regs1980** [comment]
Expert mode is deactivated in the Global CP settings.
