### ISSUE TITLE
Fertilizing & liming burns money when turning

### ISSUE THREAD

**Issue by svensigi** [Courseplay/Courseplay_FS25#106]
### Version

8.0.0.1

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Using the Lime/Fertilizer  Spreader, when turning, the CP Helper using the same amount of Money as if its spreading. Cost-Rate at spreading is right, but active when turning too

### Wie können wir diesen Fehler nachstellen?

Using the Bredal K105 with Lime or Fertilizer on a Field

### Was hätte passieren sollen?

Only using money (if activated) to spread Lime or Fertilizer if attachment is active

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18246624/log.txt)

### Screenshots

Screenshot to big

**Comment by Tensuko** [comment]
That sounds a bit like the bug from the game we found in fs22 already.
You may check this issue: https://github.com/Courseplay/Courseplay_FS22/issues/3092
