### ISSUE TITLE
tractor not slowing down on turns

### ISSUE THREAD

**Issue by Nik0194** [Courseplay/Courseplay_FS25#109]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

the tractor with a seeder on the back (bourgault air drill) does not slow down on headland corners or turns. this happens with all tools and i can't make it drive in reverse to sharpen the corners as it's attached to an air drill and cart

### How can we reproduce this?

set any course on a square field without sharpening headland corners

### What did you expect to happen?

tractor slows down like it does in fs22

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18246775/log.txt)

### Screenshots

https://github.com/user-attachments/assets/7ec4d21d-ceac-4a78-ad08-5e75e27f9f10

**Comment by Tensuko** [comment]
1) unrealistic speed
2) no sharp corner turns (must turn it on in course generator)

Won't fix that one, sry.

**Comment by Tensuko** [comment]
For that speed, it actually drives pretty good.
You can also try to use round corners set to one. I mean if you have that big machine you also have a big field, small corners not worked on is less then 0,1% fruit lost...

**Comment by Nik0194** [comment]
Ok i understand the unrealistic speed, the problem is that even if I turn on sharp corners and deactivate the driving in reverse the tractor still drives in reverse and gets stuck

**Comment by Nik0194** [comment]
I tried turning on the round corners and it still does the same, a bit better but still doesn’t slow down

**Comment by Tensuko** [comment]
There will be no slow down for that.

**Comment by Nik0194** [comment]
when i do the same in fs22 in a non square field it goes slower and adapts the speed on the headland so i don't know what i'm doing wrong. Might be that it's still in beta

**Comment by Tensuko** [comment]
With the exact same corner?

**Comment by Nik0194** [comment]
yes on fs22 with the exact same kind of field even if i have sharp corners turned off (and applied the exact same settings everywhere) it slows down like 6 meters before the corner

**Comment by Tensuko** [comment]
ok ok we can have a look but I will set this no low priority as I must say it already does it pretty good for that speed and that is rly not a priority from our side....

**Comment by Nik0194** [comment]
thx, maybe the reason it does pretty good is because i put the traction to 4 for the tractor tyres so it doesn't tip over or anything

**Comment by pvaiko** [comment]
Courseplay does not slow down in corners, speed is limited by the game engine when implements are running or in turns, depending on how sharp the turn is. I don't even know how can you even drive 45 with that rig in the straights.

If you can reproduce this with standard vehicles, vanilla config, no hacks and tricks, then reopen.

**Comment by Nik0194** [comment]
with the standard vehicles and no speed mods it doesn't go fast enough to cause the issue, i've always been modding tractors and equipment to go faster and that's never been an issue. In fs22 the tractor brakes just before the turn or in a curved field edge it doesn't go the full speed (60) but adapts it to how much the field edge curves. Anyway if you don't have any way of fixing this or it's intended behaviour i'll just get over it as it's not a game breaking issue for me

**Comment by Nik0194** [comment]
I have an update: it only happens with non articulated tractors, like the xerion in the video. I tried it with a quadtrac that also goes fast and it slows down like in fs22
