### ISSUE TITLE
Automatically replenish seeds and fertilizers at the edge of the field.

### ISSUE THREAD

**Issue by goldorel** [Courseplay/Courseplay_FS25#110]
### Version

8.0.0.1

### SP/MP

SP (Singleplayer)

### What can be done with your idea?

Hello, please tell me, will you make a function so that the seeders or lime and fertilizer spreaders are automatically filled at the edge of the field when the seeds, fertilizers or lime run out, and not like now that you have to drive up and refuel yourself? Thank you so much in advance for your reply.

### If applicable, how would the user interface look like for this enhancement?

Machinery that requires seeds, fertilizers, or lime will drive itself to the edge of the field and refuel.

### Is there an alternative?

No

### Screenshots

![Снимок экрана 2024-12-25 205044](https://github.com/user-attachments/assets/b353d574-8cb8-4329-88a7-e863944db22e)

**Comment by Tensuko** [comment]
Duplicate #36
