### ISSUE TITLE
translation correction Spanish and Spanish America

### ISSUE THREAD

**Issue by santixV8** [Courseplay/Courseplay_FS25#111]
### Version

8.0.0.1

### SP/MP

SP (Singleplayer)

### What is your question about?

Global CP settings

### What is your question?

Hello, I would like to share a correction of the translation into Spanish and American Spanish, but I don't know how to use github. I hope to have an answer and be able to collaborate with you. Greetings from Uruguay

### Screenshots

![image](https://github.com/user-attachments/assets/3b546e0f-0c8e-4566-826e-b998a9aad9e9)

**Comment by Tensuko** [comment]
You can have a look here (I hope it is not in german now...) https://docs.github.com/de/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
But when you have something ready, attach your file here and I will add it for you.
In the futur I would ofc prefer pull requests :)

**Comment by santixV8** [comment]
Yes, it is in German but I can translate it, I promise I will read it to learn later. 
So I am attaching the files for you to review. 
Thank you for your help and patience.
Santiago
[AD_spanish_translation.zip](https://github.com/user-attachments/files/18246958/AD_spanish_translation.zip)

**Comment by santixV8** [comment]
Yes, it is in German but I can translate it, I promise I will read it to learn later.
So I am attaching the files for you to review.
Thank you for your help and patience.
Santiago
[CP_spanish_translation.zip](https://github.com/user-attachments/files/18246963/CP_spanish_translation.zip)

**Comment by Tensuko** [comment]
ah, I just tought how that is AD files, there is CP one, hehe :) Thank you.

**Comment by santixV8** [comment]
Yes, I was wrong, but I also have a translation for Autodrive

**Comment by Tensuko** [comment]
The ES file contains some changes from ES to EN.
You may download the ES file and compare it to your one.
Then EA one I will add to main :)

**Comment by santixV8** [comment]
Ok, I'll check again. Thanks.

**Comment by KCHARRO** [comment]
@santixV8: Hello, I am the Spanish translator, I need to know if you will only work with the "translation_ea.xml" only or both....

**Comment by santixV8** [comment]
Hola KCHARRO, en realidad el archivo con la traducción es el mismo, solo que el cambié el nombre a translation_ea, ya que como este archivo no estaba, mi juego que está configurado en Español LA no me tomaba en cuenta la traducción de español ES y Courseplay me aparecía en inglés. 
En este momento estoy revisando nuevamente los dos archivos para corregirlos correctamente.

**Comment by KCHARRO** [comment]
That's great, I'm glad someone else is joining us...

Welcome to the team....

**Comment by santixV8** [comment]
I reviewed and made the changes based on the English translation file. Please let me know if you find any further differences.
[CP Spanish Translation.zip](https://github.com/user-attachments/files/18247142/CP.Spanish.Translation.zip)

**Comment by santixV8** [comment]
I reviewed and made the changes based on the English translation file. 
Please let me know if you find any further differences.
[CP Spanish Translation.zip](https://github.com/user-attachments/files/18247248/CP.Spanish.Translation.zip)

**Comment by Tensuko** [comment]
@KCHARRO can you explain him how to make a PR? :)
