### ISSUE TITLE
Baler needs to drive a little bit furter backwards

### ISSUE THREAD

**Issue by jawisss** [Courseplay/Courseplay_FS25#113]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

The baler does not always pick up the beginning of a grass swath.

### How can we reproduce this?

I use the Pottinger Impress 3190 and Deutz agrostar.

### What did you expect to happen?

That the baler would pick up the beginning of a swath.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18247097/log.txt)

### Screenshots

![Schermafbeelding 2024-12-25 205431](https://github.com/user-attachments/assets/5bfea1f7-caa3-4d3b-90d2-12e3edd9305c)

**Comment by Tensuko** [comment]
Did you set lower tool to early?

**Comment by jawisss** [comment]
Yes i did  :)

**Comment by Tensuko** [comment]
Would be interesting what swather you used. Or mower with swath?

**Comment by jawisss** [comment]
I have used the krone Big M

**Comment by jawisss** [comment]
> Did you set lower tool to early?

Well, I just checked to be sure, and it was not on lower early. Thought I had put it on lower early. I am very sorry for wasting your time.

**Comment by Tensuko** [comment]
No Problem.
