### ISSUE TITLE
Course generator issue without headlands

### ISSUE THREAD

**Issue by krookoo** [Courseplay/Courseplay_FS25#117]
### Version

8.0.0.0

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

When i create work with spreader on map Zielonka field 54, spreader goes beyond field.
Course generated without headlands.
If i use headland, all is generated properly.
Its low priority, only for your know.

### How can we reproduce this?

Create course without headlands using AMAZONE UX 5201 40M, field 54, map Zielonka.

### What did you expect to happen?

Low priority.
The last pass may be on the field boundary

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18247261/log.txt)

### Screenshots

![fsScreen_2024_12_25_22_32_12](https://github.com/user-attachments/assets/42ec9fad-ad9a-4e8f-9db8-0e6dd3f813dc)

**Comment by pvaiko** [comment]
Courses with no headland on a non-rectangular field will always leave the field, otherwise 100% coverage cannot be guaranteed.
