### ISSUE TITLE
Error, unable to load map on my savegame

### ISSUE THREAD

**Issue by bullfarmer** [Courseplay/Courseplay_FS25#120]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

Getting an error when trying to load courseplay on to my current savegame. Stops loading at 98 percent. 
Pulls this error; 

2024-12-26 12:13 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
dataS/scripts/vehicles/specializations/AIDrivable.lua:728: invalid argument #1 to 'max' (number expected, got nil)
2024-12-26 12:13 Info: Failed to request rc, HTTP code 0. 

Tried to load with no other mods other than courseplay still brings up the error.

Only happens on my current savegame. It will load up with no error when starting new savegame 

I do have fields i have created so possibly this???

### How can we reproduce this?

Load courseplay on to old savegame rather than new on Zielonka map

### What did you expect to happen?

Able to load courseplay onto my current savegame but would need to make a new savegame for it to load in

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18247447/log.txt)

### Screenshots

NA

**Comment by Tensuko** [comment]
Error in another mod, maybe that pack from lsfm with those tools.
Wont fix.
