### ISSUE TITLE
FSG MA Says maleware detected in CP

### ISSUE THREAD

**Issue by JTerkGaming** [Courseplay/Courseplay_FS25#121]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

Loading a mods folder using FSG Mod Assistant, with Course Play present, shows a warning about Maleware detected. I believe I have found the lua script in question too. 

FS25_Courseplay.zip/scripts/test/mock-GiantsEngine.lua has a delete function with in it. 
I don't think that should be in there.

### How can we reproduce this?

Just run FSG Mod Assistant with Courseplay in the mods folder.

### What did you expect to happen?

I was told about it from someone else. So I went searching lua files to see if I could find one that could be the culprit.

### Attach your log.txt!

I don't have a log file as that error within FSG MA, doesn't show up in game.

### Screenshots

![Screenshot 2024-12-25 175951](https://github.com/user-attachments/assets/52ca3284-dc06-4beb-9d25-6f957e595340)

**Comment by Tensuko** [comment]
Problem of your weird tool then. Wont fix, its not malware.

**Comment by JTerkGaming** [comment]
Of course you'd list it as won't fix, even though there is a big issue. There is a delete code in one of the lua's. And that's what FSG Mod Assistant looks for, so people don't have their mods, saves, ect deleted from a mod. I will never use Course Play again. I used to support you guys. I won't ever again. You wouldn't even look into it. such a shame, as CP is a very useful tool. But I refuse to use a mod from a creator that won't look into or fix the most minute of issues.

**Comment by Tensuko** [comment]
You tell me that YOUR Tool deleted a code from CP and tell US we did a mistake?
We have that code in there for a reason and NO one have any problem with that code.
It is just your tool doing a false detection!

**Comment by JTerkGaming** [comment]
unsubbed

**Comment by Tensuko** [comment]
Just for full documentation, that file is 3 years old.
https://github.com/Courseplay/Courseplay_FS25/blame/main/scripts/test/mock-GiantsEngine.lua
