### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by JGum1036** [Courseplay/Courseplay_FS25#122]
### Version

8.0.0.0

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

When buying and customizing a vehicle in the store, I sometimes get the following error and then it locks the game and I have to quit out and restart. I was not using courseplay at the time of the error. 2024-12-25 23:05 Error: Running LUA method 'update'.
C:/Users/JBall/OneDrive/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/specializations/CpCourseManager.lua:227: attempt to index nil with 'courses'

### How can we reproduce this?

.

### What did you expect to happen?

.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18249496/log.txt)

### Screenshots

.

**Comment by Tensuko** [comment]
You are using an old Version https://github.com/Courseplay/Courseplay_FS25/releases
It is already fixed in 8.0.0.1 https://github.com/Courseplay/Courseplay_FS25/issues/62
