### ISSUE TITLE
HowTo configure Grapes Leaf Cutter

### ISSUE THREAD

**Issue by Rodagasto** [Courseplay/Courseplay_FS25#125]
### Version

8.0.0.1

### SP/MP

SP (Singleplayer)

### What is your question about?

Course creation

### What is your question?

What is the ideal configuration for the leaf cutter when preparing the vines?
My observation is that none of the courses works all lanes since the tool is mounted to the left. In case of up down and spirals every other lane is skipped. Technically one need to drive up/down the same lane then skip one and repeat. 
For mulching, cultivating and fertilizing it wors like charm when I disabled the limitation for turning on the filed only otherwise the turn is cut and one gets stuck in between the vines.

### Screenshots

![FS25_Cp_8001_UpDownVines](https://github.com/user-attachments/assets/e870ac03-80a9-4b66-8a40-b4f09b7edf72)

**Comment by Tensuko** [comment]
It is written in the help menu.
On vine and drive with offset if I remember correct.

**Comment by Tensuko** [comment]
![grafik](https://github.com/user-attachments/assets/44699484-6aac-4f09-812c-a42dfb2f40d3)

**Comment by Rodagasto** [comment]
> `The pre-pruner needs to drive left from the vines but works on the vine, so you have to choose to work on the vine, but drive with an offset.`

I'll try it thanks. Before I used right to the vine with offset which kinda worked but I had the issue that some vines were worked on twice and every other was skipped.

**Comment by Rodagasto** [comment]
![Screenshot 2024-12-27 124904](https://github.com/user-attachments/assets/f99bf566-c6b6-4464-9bdd-953a74854179)
![Screenshot 2024-12-27 130515](https://github.com/user-attachments/assets/e1f6ad01-a43e-4329-bca8-faccfc389fa8)
I wasn't able to get it running even with reading the manual again and the hints you provided.

I started to record my own tracks now and attached them for reference. That also highlights why normal up down will not work when one have a onesided tool.

**Comment by Tensuko** [comment]
Why is the record button on?
That is not for recording tracks.
You have to set it to ON the vines and it will work.....

**Comment by Rodagasto** [comment]
I tried with "On the Vine" and different Tool offsets from -0.8 to -1.6. Default is -1.2. With all of these the tractor keeps running into or sometimes up the vines and gets stuck.

I'm really sorry to bother you with that.

The record button was on because I decided to try and record my own course since I wasn't successful with the default settings. 
If you may post a screenshot of your config and the generated course it may help.

**Comment by Tensuko** [comment]
Record is ONLY for recording a custom field border!

Wait for my settings....

**Comment by Tensuko** [comment]
![grafik](https://github.com/user-attachments/assets/2059b266-b190-4b6a-8564-b48206c72473)
![grafik](https://github.com/user-attachments/assets/70cab0b9-3fb5-424e-81b3-45628f9ce773)
![grafik](https://github.com/user-attachments/assets/75aeb176-621f-4e6f-8538-a1022533a63f)

Vine work turns are a bit broken but that I will check later.

**Comment by Rodagasto** [comment]
Ok I see you mount the tool in the front, I had it in the back.

But by looking at you screenshot for the course vines 1 and 2 from the right will be work (right turns) but 3 will be skipped 4 due to a left turn. 4 and 5 are working again.

**Comment by Rodagasto** [comment]
> Record is ONLY for recording a custom field border!
> 
> Wait for my settings....

Ah I see, new to CP and experimenting with some features^^

**Comment by Tensuko** [comment]
No, all vines will be worked on because the driver will always make sure the tool will drive ON the vine on every vine.
The Tractor does not have to drive between every one... the toll only needs to work on the vines where the course is, not inbetween.

**Comment by Rodagasto** [comment]
Ok I can finally acknowledge with front mount tool everything works like a charm -thanks for your patience and explanation.
