### ISSUE TITLE
Round Bale Pick-Up

### ISSUE THREAD

**Issue by Woodshock** [Courseplay/Courseplay_FS25#127]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

I set the tractor with Anderson Group RBM 2000 on the field I opened CP and I selected collect not wrapped/wrapped bales All bales so the HUDS showed 16 bales to collect I pressed the play button and it started fine but after picking up 3 bales he claims NO COURSE FOUND while it should work without a course on the help menu 

### How can we reproduce this?

Not sure 
![Screenshot_3](https://github.com/user-attachments/assets/57e62e18-1df9-4076-b6b4-17ce9fd68fcd)
![Screenshot_4](https://github.com/user-attachments/assets/4fe71317-cdcf-4544-84ed-7aaa750aa344)

### What did you expect to happen?

Loading my bales tbh :-)

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18252338/log.txt)

### Screenshots

![Screenshot_3](https://github.com/user-attachments/assets/11b54348-5368-4451-9f22-42e50d6deaeb)
![Screenshot_4](https://github.com/user-attachments/assets/c468785a-426e-487a-8e79-d9a7e7fb3a59)

**Comment by Tensuko** [comment]
Tested with 1.8m offset or even 1.9?

**Comment by Tensuko** [comment]
Found the problem.... its a annoying one but we will find a solution.

**Comment by Woodshock** [comment]
Now I have other issue asswell I set the mac don track a copy the track but that stupid combine refuse to move and will try a smaller tractor and offset

**Comment by Woodshock** [comment]
![Screenshot_5](https://github.com/user-attachments/assets/f62824f8-8242-4beb-b083-fb9691a1e329)
drives a few meter and refuses to do anything else frustrating as hell on youtube every one click click and everything works why not with me

**Comment by Tensuko** [comment]
Please dont post more problems in one issue. The macDon is known in another issue.

**Comment by Tensuko** [comment]
Should be all fixed
