### ISSUE TITLE
F1 Vehicle information is not displayed.

### ISSUE THREAD

**Issue by Manyak007** [Courseplay/Courseplay_FS25#128]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

Vehicle information is not displayed.

### How can we reproduce this?

just use CP

### What did you expect to happen?

I expected the hint to be available with the vehicle.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18252666/log.txt)

### Screenshots

![1](https://github.com/user-attachments/assets/6e7cbe08-8435-42f5-b996-1f04fc0d8fed)

**Comment by Tensuko** [comment]
Fixed on next Release. #91

**Comment by Manyak007** [comment]
I'm sorry, I searched but I didn't find anything.
