### ISSUE TITLE
Rechtsklick öffnet jedesmal den HUD mit, obwohl in der Steuerung angepasst.

### ISSUE THREAD

**Issue by Stefan0410** [Courseplay/Courseplay_FS25#130]
### Version

8.0.0.0

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Sobald ich im Spiel den Rechtsklick der Maus betätige, öffnet sich das Courseplay HUD gleich mit. 
In den Einstellungen habe ich nur aktiviert: HUD öffnen bei Taste "Löschen" und Mauszeiger sichtbar bei "Rechtsklick"

### Wie können wir diesen Fehler nachstellen?

Einfach im Spiel den Rechtsklick betätigen bei geschlossenem HUD

### Was hätte passieren sollen?

Mauszeiger sichtbar - aber HUD geschlossen bleiben

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18253106/log.txt)

### Screenshots

Ein Screenshot ist hier nicht hilfreich

**Comment by Tensuko** [comment]
Funktioniert so wie es soll.
Mauszeiger ohne hud gibt es so nicht außer bei cts.

Und bitte updaten bevor du ein Issue auf machst.
