### ISSUE TITLE
Combine refuse to work with copy course

### ISSUE THREAD

**Issue by Woodshock** [Courseplay/Courseplay_FS25#131]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

I set everything right I even tryed to select the field sometimes he drives circles and nothing and then he completely refuses to do anything 

### How can we reproduce this?

not sure how 

### What did you expect to happen?

swadding my field 

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18253209/log.txt)

### Screenshots

![harvesting 1](https://github.com/user-attachments/assets/3708a50b-6ecc-4168-b655-eacc9d265f19)
![harvesting](https://github.com/user-attachments/assets/1e7c9d28-3bab-4289-ab66-ff4a76549169)
![Screenshot_5](https://github.com/user-attachments/assets/d93135a0-96ba-4743-ad5b-de55bb4b7c0c)
![Screenshot_6](https://github.com/user-attachments/assets/1b80a696-a0f3-42ce-9ff5-b89ef602c23d)
![Screenshot_7](https://github.com/user-attachments/assets/80c024ab-f184-46d8-9059-968a2eff7e87)

**Comment by Tensuko** [comment]
That is macDon and is known.
Duplicate.

**Comment by Woodshock** [comment]
you need to fix this bug do you want to remove this one

**Comment by Tensuko** [comment]
We will but we know this issue. Dont need it twice.
