### ISSUE TITLE
Selbst Platziertes Reisfeld wird nicht richtig erkannt

### ISSUE THREAD

**Issue by NeonRider1999** [Courseplay/Courseplay_FS25#132]
### Version

8.0.0.1

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Ich habe selber ein Reisfeld auf der Amikarte auf Feld 7 und 9 gebaut. Problem ist das Cp nicht die neuer Form des Feldes (trotz aktiviert Bevorzugung des eigenen Feldrandes) erkennt, sonder noch die alten Feldumrisse nimmt (diese sind kleiner wie das neue Reisfeld). Vom Giants Helfer wird das ohne Probleme erkannt.

Ich habe auch vorher versucht die alten Felder zu übermalen und dann erst das Reisfeld zu setzen, auch das hat nicht geholfen.

### Wie können wir diesen Fehler nachstellen?

Am besten ein Reisfeld auf schon bestehende Felder pflanten

### Was hätte passieren sollen?

.

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18253471/log.txt)

### Screenshots

![fsScreen_2024_12_26_15_33_03](https://github.com/user-attachments/assets/948d0613-1fbb-4826-833b-6db930e95211)
![fsScreen_2024_12_26_15_36_10](https://github.com/user-attachments/assets/1e1760b9-54e6-4bce-980f-6d15dd06ce87)

**Comment by Tensuko** [comment]
Hast du mal ein Savegame für mich?

**Comment by NeonRider1999** [comment]
Ja habe ich.
[savegame1.zip](https://github.com/user-attachments/files/18266057/savegame1.zip)
 
Savegame Ordner ist in der Zip Datei

**Comment by Tensuko** [comment]
@pvaiko Slot5
![grafik](https://github.com/user-attachments/assets/05930bae-fd31-41f1-8d06-b81af863e856)

**Comment by pvaiko** [comment]
Funktioniert es mit dem Giants Helfer?

**Comment by NeonRider1999** [comment]
Ja mit dem Giants Helfer klappt es ohne Probleme

**Comment by LanWolf** [comment]
Here the same problem, rice field is not rendered correct in Courseplay, AI worker no problem

![courseplay_ricefield_issue](https://github.com/user-attachments/assets/65151099-0573-405d-b681-1772d91e2402)

![AI Helper Ricefield](https://github.com/user-attachments/assets/ba83eeea-a5a8-4bf5-bceb-aecbb0c6f15a)
