### ISSUE TITLE
Info Hud seit neuester Version (8.0.0.1) leer

### ISSUE THREAD

**Issue by Markus4nich** [Courseplay/Courseplay_FS25#134]
### Version

8.0.0.1

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

seit der Installation der neuesten Version ist das Info Hud mit empfohlenen Tastenkombinationen etc. leer. Habe getestet, ob es an anderen Mods liegt. (Auto drive etc.) aber nur wenn CP mit der map geladen wurde besteht dieses problem

### Wie können wir diesen Fehler nachstellen?

Nur neueste version installieren und dann spielen

### Was hätte passieren sollen?

in dem Info Hud siehe Screenshot sollten eigentlich tastenbefehle etc. stehen für kommende Aktionen

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18255177/log.txt)

### Screenshots

![image](https://github.com/user-attachments/assets/fe565626-14dd-4e30-a813-a64726e5718e)

**Comment by Tensuko** [comment]
Ist in nächster Version gefixt.

**Comment by Markus4nich** [comment]
Sehr geil, könnt ihr schon grob vorhersagen, wann die nächste Version erscheint?

Ihr macht echt einen super Job

**Comment by BalticHawk** [comment]
Eine Minute vor deiner Nachricht.
