### ISSUE TITLE
Übergabe von AD zu CP

### ISSUE THREAD

**Issue by franky-bb** [Courseplay/Courseplay_FS25#135]
### Version

8.0.0.1

### SP/MP

SP (Singleplayer)

### Um was geht es bei deiner Frage?

Kurserstellung

### Wie lautet deine Frage?

Den Kurs zum Feld erstellt man mit AD. So wie im LS22. Man konnte auch festlegen, ob nach Ankunft zum Feld die Bearbeitung mit CP fortgesetzt wird. Leider übergibt AD nicht an CP. Der Trecker bleibt einfach am Feld stehen. Hab ich bei den Einstellungen irgend etwas übersehen? oder ist die Funktion noch nicht verfügbar. Was aber funktioniert, dass nach Beendigung der Bearbeitung auf dem Feld der Traktor automatisch zum Parkpunkt zB. auf den Hof zurückfährt. Das bedeutet, CP übergibt an AD. Bin mir nicht sicher, ob die fehlende Funktion an AD oder an CP liegt.

**Comment by regs1980** [comment]
@franky-bb 
Wie sieht dein AD HUD aus, mal bitte Screenshot?

**Comment by franky-bb** [comment]
![Screenshot 2024-12-26 222344](https://github.com/user-attachments/assets/8c7146ec-e82c-45e5-8833-b194eaeec7b1)

Es spielt keine Rolle, ob der AD Kurs neben dem Feld oder auf dem Feld endet.

**Comment by Tensuko** [comment]
Kein CP Icon im AD Hud aktiv.

**Comment by franky-bb** [comment]
Kannst du mir sagen, was ich falsch eingestellt habe.

**Comment by Goofy78** [comment]
![398803858-8c7146ec-e82c-45e5-8833-b194eaeec7b1](https://github.com/user-attachments/assets/298f7b29-e460-4b45-98d5-bbd0b98bfe67)

Mach mal Rechtsklick drauf und dann erscheint das CP-Logo .... dann nur noch mit links aktivieren und AD losschicken

**Comment by regs1980** [comment]
@franky-bb 
https://github.com/Stephan-S/FS25_AutoDrive/wiki/INFO:-HUD-Button
