### ISSUE TITLE
Forage Harvester does not work with grass

### ISSUE THREAD

**Issue by dylboy92** [Courseplay/Courseplay_FS25#136]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

forage harvesters wont start a course on a grass field. when you press the play button to start the course nothing happens just a error appears in log

2024-12-27 10:33 Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/Cutter.lua:1494: invalid argument #1 to 'ipairs' (table expected, got nil)

### How can we reproduce this?

windrow a mowed field use a forage harvester to try chop the grass into a trailer. when you press start course nothing happens just get a error in log

### What did you expect to happen?

when you press start the harvester will follow the course and chop the grass into a trailer (as it does in fs22)

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18255573/log.txt)

### Screenshots

![2300320_20241227103432_1](https://github.com/user-attachments/assets/f7885182-af5a-4093-b972-7cf767cb98bf)

**Comment by Tensuko** [comment]
Same Error as in #60
