### ISSUE TITLE
Cutting grass on Field 25 in River map skips one row.

### ISSUE THREAD

**Issue by Jotte71** [Courseplay/Courseplay_FS25#137]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

It skips over one of the rows, but the row is marked so it should work.  I set three (3) Headlands with 3 rounded corners. 
The Implement is grass cutters KUHN GMD 8730 FF (back of tractor) an d KUHN 3123 F (Front of tractor).
![20241226230926_1](https://github.com/user-attachments/assets/ee8f9eb4-d52e-428c-9588-f89d5cd6e6a8)

### How can we reproduce this?

I set three (3) Headlands with 3 rounded corners. 
The Implement is grass cutters KUHN GMD 8730 FF (back of tractor) an d KUHN 3123 F (Front of tractor).
The rest of the settings is standard.

### What did you expect to happen?

That it would do all the markers

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18255707/log.txt)

### Screenshots

![20241226230926_1](https://github.com/user-attachments/assets/491f1915-a5fe-4a3f-a9ad-59858ff80c86)

**Comment by Tensuko** [comment]
Should be the same problem as in #79
