### ISSUE TITLE
Excavator + attachable tool brings LUA Error, after save the game and reload: Error: Running LUA method 'loadSharedI3DFileAsyncFinished'

### ISSUE THREAD

**Issue by KLAYPLEX** [Courseplay/Courseplay_FS25#138]
### Version

8.0.0.1

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Ich kann einem Spielstand mit CP aktiviert nichtmehr joinen, Fehler Error: Running LUA method 'loadSharedI3DFileAsyncFinished'

Bleibt bei 98% stehen beim Laden

### Wie können wir diesen Fehler nachstellen?

Keine Ahnung, habe mehrfach versucht ohne CP zu starten und alle KIs zu deaktivieren ect.

### Was hätte passieren sollen?

Spiel Laden

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18255829/log.txt)

### Screenshots

bei 98% gestoppt

**Comment by Tensuko** [comment]
Mod Error vermutlich das pack von lsfm oder wie die hießen. Schubkarre usw.

**Comment by KLAYPLEX** [comment]
Vermute ich nicht, auch mit nur Courseplay mod aktiv kann ich nicht laden

**Comment by KLAYPLEX** [comment]
Modsettingsordner auchversucht zu löschen

**Comment by KLAYPLEX** [comment]
Habe jetzt alle Mods Deaktiviert, SPiel gestartet, Gespeichert, Beendet, neu geladen mit Courseplay als einzige mod, wieder bie 98% Stop

**Comment by KLAYPLEX** [comment]
> Mod Error vermutlich das pack von lsfm oder wie die hießen. Schubkarre usw.

Liegt nicht an andere Mods

**Comment by Tensuko** [comment]
Savegame?

**Comment by KLAYPLEX** [comment]
> Savegame?


[Save1.zip](https://github.com/user-attachments/files/18255914/Save1.zip)

**Comment by KLAYPLEX** [comment]
ich versuch auch die ganze zeit herauszufinden woran es liegt

**Comment by KLAYPLEX** [comment]
Problem gefunden

**Comment by KLAYPLEX** [comment]
> Mod Error vermutlich das pack von lsfm oder wie die hießen. Schubkarre usw.

Habe das Problem gefunden, das letzte Fahrzeug das ich gekauft habe habe ich aus dem spiel gelöschtjetzt kann ich wieder laden

**Comment by KLAYPLEX** [comment]
den großen Baumbagger ec380DL + thx180


<vehicle filename="data/vehicles/volvo/ec380DL/ec380DL.xml" uniqueId="vehicle6ab21d858b00148e78ea018e4bc9b78b" age="0.000000" price="365500.000000" farmId="1" propertyState="LEASED" operatingTime="864.599792" selectedObjectIndex="2" subSelectedObjectIndex="1">
<component index="1" position="-591.755 46.980 169.843" rotation="-4.51 -88.04 4.29"/>
<component index="2" position="-590.802 48.906 169.800" rotation="-3.90 -87.73 3.67"/>
<configuration name="fillUnit" id="1" isActive="true"/>
<configuration name="animation" id="1" isActive="false"/>
<configuration name="animation" id="3" isActive="true"/>
<configuration name="automaticArmControlHarvester" id="1" isActive="false"/>
<configuration name="automaticArmControlHarvester" id="3" isActive="true"/>
<configuration name="motor" id="1" isActive="true"/>
<configuration name="cylindered" id="1" isActive="false"/>
<configuration name="cylindered" id="3" isActive="true"/>
<configuration name="component" id="1" isActive="false"/>
<configuration name="component" id="3" isActive="true"/>
<configuration name="attacherJoint" id="1" isActive="false"/>
<configuration name="attacherJoint" id="3" isActive="true"/>
<configuration name="design" id="1" isActive="false"/>
<configuration name="design" id="3" isActive="true"/>
<configuration name="design2" id="2" isActive="true"/>
<configuration name="vehicleType" id="1" isActive="false"/>
<configuration name="vehicleType" id="3" isActive="true"/>
<configuration name="design4" id="1" isActive="true"/>
<configuration name="design3" id="1" isActive="true"/>
<configuration name="wheel" id="LIZARD_DEFAULT" isActive="true"/>
<washable>
<dirtNode amount="0.028698" wetness="0.000000"/>
<dirtNode amount="0.256498" wetness="0.000000" snowScale="0.000000"/>
<dirtNode amount="0.000000" wetness="0.000000"/>
<dirtNode amount="0.299894" wetness="0.000000" snowScale="0.000000"/>
<dirtNode amount="0.000000" wetness="0.000000"/>
</washable>
<wearable damage="0.002145">
<wearNode amount="0.034486"/>
</wearable>
<cylindered>
<movingTool rotation="0.309033"/>
<movingTool rotation="-34.012383"/>
<movingTool rotation="122.090912"/>
<movingTool rotation="-4.312257"/>
</cylindered>
<wheels lastConfigId="LIZARD_DEFAULT"/>
<enterable activeCameraIndex="1" isTabbable="true" isLeavingAllowed="true">
<camera rotation="-19.82 54.48 0.00" translation="0.000 0.000 9.700" zoom="9.700010" fovY="54.432205"/>
<camera rotation="-23.00 180.00 0.00" translation="1.035 2.300 0.450" zoom="2.562068" fovY="77.000008"/>
<camera rotation="184.70 -20.31 180.00" translation="0.000 0.000 0.000" zoom="0.000010" fovY="75.000008"/>
</enterable>
<fillUnit>
<unit index="1" fillType="DIESEL" fillLevel="599.996216"/>
</fillUnit>
<drivable cruiseControl="10" cruiseControlReverse="10"/>
<aiFieldWorker isActive="false"/>
<aiJobVehicle isAIStartAllowed="true"/>
<aiAutomaticSteering courseWasActive="true" isOnField="false"/>
<aiModeSelection currentMode="WORKER"/>
<attacherJoints comboDirection="-1">
<attachedImplement jointIndex="1" moveDown="false" attachedVehicleUniqueId="vehicle8f8b7973223c643d0fce310f18d4fa73" inputJointIndex="1"/>
</attacherJoints>
<FS25_parkVehicle>
<parkVehicle>
<player id="xxthh" isParked="false"/>
</parkVehicle>
</FS25_parkVehicle>
<FS25_EasyArmControlToggle>
<easyArmControlToggle modActive="true"/>
</FS25_EasyArmControlToggle>
<FS25_ClickToSwitch>
<clickToSwitch assignment="false"/>
</FS25_ClickToSwitch>
</vehicle>
<vehicle filename="data/vehicles/tmcCancela/thx180/thx180.xml" uniqueId="vehicle8f8b7973223c643d0fce310f18d4fa73" age="0.000000" price="23000.000000" farmId="1" propertyState="LEASED" operatingTime="773.261230">
<component index="1" position="-598.674 48.730 170.359" rotation="-178.79 -1.91 150.25"/>
<washable>
<dirtNode amount="0.100411" wetness="0.000000"/>
</washable>
<wearable damage="0.001878">
<wearNode amount="0.075416"/>
</wearable>
<cylindered>
<movingTool rotation="8.668405"/>
</cylindered>
<attachable isDetachingBlocked="false"/>
<attacherJoints comboDirection="-1"/>
<plow rotationMax="false"/>
<FS25_EasyArmControlToggle>
<easyArmControlToggle modActive="true"/>
</FS25_EasyArmControlToggle>
</vehicle>

**Comment by KLAYPLEX** [comment]
ich versuche das zu rekonstruieren

**Comment by KLAYPLEX** [comment]
> Savegame?

Sobald ich einen ec380 lease und ein thx180 Dran mache lässt sich das spiel mir Courseplay nichtmehr laden, ohne courseplay kein problem

**Comment by Tensuko** [comment]
Ich bekomme für jeden post eine mail. Desshalb bitte nicht jeden gedanken hier einzeln schreiben, zur not editieren...
Ich gucks mir an...

**Comment by KLAYPLEX** [comment]
geht klar, aber Ursache habe ich ja gefunden :)

**Comment by Silver45711** [comment]
Hallo habe den selben feher bin aber neu in den game wie kann ich den ein fahrzeug löschen ohne ins Game zu kommen ?
Danke für eure Infos und Hilfe
habe schon einige male neu angefangen. Wäre cool wenn ich das wieder hinbekommen könnte
Habee meine Log.txt mal hochgeladen falls es hilft
[log.txt](https://github.com/user-attachments/files/18349106/log.txt)

**Comment by Tensuko** [comment]
Available mod:  (Version: 8.0.0.0) FS25_Courseplay
https://github.com/Courseplay/Courseplay_FS25/releases
Delete the folder.
Download only from there the .zip file and place it in mods folder, nothing more.

**Comment by Silver45711** [comment]
Dankeschön hat geklappt.

**Comment by Silver45711** [comment]
Hallo habe schon wieder ein Problem mit dieser lua meldung. Hatte gestern abend ausgemacht und wollte grade Starten geht nur bis 89% dann nichts mehr habe das Ahtuelle Courseplay drauf meine 8.0.0.6 
Diese meldung kommt nun:
C:/Users/mskou/OneDrive/Dokumente/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/specializations/CpVehicleSettings.lua:421: attempt to perform arithmetic (div) on nil and number
Ich hänge mal meine Log und savegame mit dran

[log.zip](https://github.com/user-attachments/files/18576638/log.zip)
[savegame3.zip](https://github.com/user-attachments/files/18576637/savegame3.zip)

Danke im voraus für eure hilfe mal wieder

gruß
Silver
