### ISSUE TITLE
helper going of course

### ISSUE THREAD

**Issue by HerrBert-44** [Courseplay/Courseplay_FS25#139]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

The helper keep going of course and like really far away

### How can we reproduce this?

.

### What did you expect to happen?

.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18255842/log.txt)

### Screenshots

![image](https://github.com/user-attachments/assets/0838f9ae-2ba4-4c2a-b052-4fe08bdf1aa7)
![image](https://github.com/user-attachments/assets/3319407b-d435-44f8-b3ca-9cf728c2007b)

**Comment by Tensuko** [comment]
Load latest version and fill in the complete template.
