### ISSUE TITLE
combine does not unload when worker is active!

### ISSUE THREAD

**Issue by AmericanFarmersGaming** [Courseplay/Courseplay_FS25#142]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

when working in the field the worker in the combine does not unload into any trailer. you have to fire the worker and unload your self

### How can we reproduce this?

harvest a field and get the worker full of grain and go up to the worker and try to get them to unload into the trailer or grain cart.

### What did you expect to happen?

i expected the combine to unload into the trailer or grain cart

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18256652/log.txt)

### Screenshots

N/A

**Comment by Tensuko** [comment]
Old version
Qhat combine
Self unload or with a combine unloader or by player?

**Comment by AmericanFarmersGaming** [comment]
this is for fs25 and it still dont want to unload into any trailers and have checked for mod confects and it still will not unload into trailers with no mods and only courseplay

**Comment by Tensuko** [comment]
Your log say a lot of FS22_ as mods

**Comment by Tensuko** [comment]
Farming Simulator 22
  Version: 1.11.0.0 b25287
And even an old game version.

**Comment by AmericanFarmersGaming** [comment]
![Screenshot 2024-12-28 203049](https://github.com/user-attachments/assets/136e8673-8eef-4070-bdf1-bd7118973cdf)
 no this is the log i sent it tells me it is fs25

**Comment by AmericanFarmersGaming** [comment]
i will try it again after this latest update and get back to you on this

**Comment by Tensuko** [comment]
Ok
