### ISSUE TITLE
cant join server

### ISSUE THREAD

**Issue by FarmerJonny** [Courseplay/Courseplay_FS25#143]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

MP (Multiplayer)

### What happened?

after i downloaded and installed version .2, i now can not get into the server. it says connecting but stays at 0 percent. myself and the other players on my server experienced this. we are only able to log into the server after disabling courseplay.

### How can we reproduce this?

update to latest version of courseplay. try to log into a dedicated server that has updated version installed.

### What did you expect to happen?

i expected to be able to log into the server

### Attach your log.txt!

NA

### Screenshots

![image](https://github.com/user-attachments/assets/234ddab1-fe06-4d59-b4bd-4a9186e89dd5)

**Comment by Tensuko** [comment]
Old version
