### ISSUE TITLE
GPS Field Mapping

### ISSUE THREAD

**Issue by WernerHerr** [Courseplay/Courseplay_FS25#145]
### Version

8.0.0.0

### SP/MP

SP (Singleplayer)

### What can be done with your idea?

When creating a new field on a map like New Frontier. Would it be possible to GPS map the outline of a field and let Coursleplay fill in the field with a plow or mower?

### If applicable, how would the user interface look like for this enhancement?

It could just be an additional option. The player would have to physically plow the outline.

### Is there an alternative?

No

### Screenshots

Just a thought.

**Comment by Tensuko** [comment]
Not planed.
