### ISSUE TITLE
Maleware im lua script???

### ISSUE THREAD

**Issue by OpiGunnar** [Courseplay/Courseplay_FS25#146]
### Version

8.0.0.1

### SP/MP

egal

### Um was geht es bei deiner Frage?

weiteres später

### Wie lautet deine Frage?

muss man sich gedanken machen???

### Screenshots

<img width="1225" alt="Screenshot_1" src="https://github.com/user-attachments/assets/2adc1c28-90f8-412d-93b7-c442f1a71edb" />

**Comment by Tensuko** [comment]
Das ist seit 3 Jahren drin. Nein muss man nicht.

**Comment by OpiGunnar** [comment]
ok,wird mir zum erstenmal angezeit,deshalb lieber mal nachfragen
