### ISSUE TITLE
erste reihe nach dem vorgwende

### ISSUE THREAD

**Issue by OpiGunnar** [Courseplay/Courseplay_FS25#148]
### Version

8.0.0.1

### SP/MP

MP (Multiplayer)

### Um was geht es bei deiner Frage?

Kurserstellung

### Wie lautet deine Frage?

hallo,
der courseplay helfer lässt inner nach dem vorgewnde die erste gerade aus,mach ich was falsch (einstellungs technisch?)

### Screenshots

<img width="769" alt="Screenshot_3" src="https://github.com/user-attachments/assets/e760e5a0-86f1-42e2-a99d-8f3ab030a005" />

**Comment by Tensuko** [comment]
#79
