### ISSUE TITLE
The worker from CoursePlay doesn’t go to unload the harvester.

### ISSUE THREAD

**Issue by RomanianBuZz** [Courseplay/Courseplay_FS25#149]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

Hello guys! I’m not sure if this is a bug or if the feature hasn’t been implemented yet, but when I use the in-game worker on a harvester, and it’s full of grain, CoursePlay doesn’t go to unload it. Does the harvester need to have a CoursePlay worker for unloading to work, or could you implement it so that it also works with the default in-game worker? P.S. I’d prefer not use the AutoDrive mod.

### How can we reproduce this?

I assign the in-game worker to harvest, the harvester gets full and extends the pipe, but the worker from CoursePlay doesn’t move to unload the harvester.

### What did you expect to happen?

I want CoursePlay to unload the harvester even when I’m using the default in-game worker. I don't want to use autodrive

### Attach your log.txt!

No need

### Screenshots

No need

**Comment by Tensuko** [comment]
CP only unload CP harvester.
