### ISSUE TITLE
MacDon PW8

### ISSUE THREAD

**Issue by Snakebite203** [Courseplay/Courseplay_FS25#150]
### Version

8.0.0.2

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Kurs geladen, Drescher sollte den Kurs abarbeiten und die Schwad dreschen. Beim aktivieren von Courseplay bleibt der Drescher sofort stehen und macht nix. Courseplay bring nur die Meldung, dass "Die Arbeit beendet" ist. 

### Wie können wir diesen Fehler nachstellen?

Bitte prüfen und Update für Courseplay, dass der Drescher mit MacDon PW 8 arbeitet. 

### Was hätte passieren sollen?

Der Drescher sollt den Kurs abarbeiten und die Schwad dreschen. 

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18261156/log.txt)

### Screenshots

![fsScreen_2024_12_27_15_37_12](https://github.com/user-attachments/assets/267180ff-7067-41c4-8fa7-d7ce74dd4974)

**Comment by BalticHawk** [comment]
Vorher schauen, ob es Fehlermeldungen gibt, hilft manchmal. 😉

#60 duplicate

**Comment by Snakebite203** [comment]
Sorry 🙃
