### ISSUE TITLE
Worker took off after completing a headland

### ISSUE THREAD

**Issue by Wezzaa1** [Courseplay/Courseplay_FS25#151]
### Version

8.0.0.2

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

https://medal.tv/games/farming-simulator-25/clips/jmWNbXKoTestBdoK3?invite=cr-MSxvaFMsMjYyNTg0MDEs

### How can we reproduce this?

Hutan Pantai Top Rice Patty field transplanting with one headland set

### What did you expect to happen?

The worker to continue onto the next headland

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18261623/log.txt)

### Screenshots

https://medal.tv/games/farming-simulator-25/clips/jmWNbXKoTestBdoK3?invite=cr-MSxvaFMsMjYyNTg0MDEs

**Comment by pvaiko** [comment]
For the record: this is the pathfinder failing with goal node invalid.

**Comment by pvaiko** [comment]
11c6c02 should fix this
