### ISSUE TITLE
Arbeitsgeschwindigkeit Passt nicht MacDon

### ISSUE THREAD

**Issue by Draku1986** [Courseplay/Courseplay_FS25#152]
### Version

8.0.0.2

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Ich mähe gerade mit dem MacDon M1240 und dem Schneidwerk R216 SP (Original Giants MOD).
Laut Spiel sollte er 24km/h Workspeed haben, bei CP fährt er aber nur mit 12km/h.
Mit dem Giantshelfer fährt er die 24km/h und manuell auch.
Im Fahrzeug-Menü kann ich auch nur maximal 12km/h einstellen.

### Wie können wir diesen Fehler nachstellen?

Mähe ein Feld mit dieser Fhz-Kombi :)

### Was hätte passieren sollen?

Mit voller Arbeitsgeschwindigkeit mähen ;)

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18262638/log.txt)

### Screenshots

![fsScreen_2024_12_27_19_12_20](https://github.com/user-attachments/assets/9154d92d-07d1-4f42-b403-a3aecb35c964)

**Comment by Tensuko** [comment]
Magic?
![grafik](https://github.com/user-attachments/assets/e0d21281-2a16-4492-ac1e-7fd0b0fab44b)
![grafik](https://github.com/user-attachments/assets/86bd2cf4-70e1-454e-ac47-1a52ff775f3a)
