### ISSUE TITLE
Rcr row crop planting

### ISSUE THREAD

**Issue by Grantchromeshop** [Courseplay/Courseplay_FS25#155]
### Version

8.0.0.2

### SP/MP

SP (Singleplayer)

### What can be done with your idea?

Giants helper will plant rcr row crop. Courseplay skips rows and stops planting in certain areas.
![7e37169e-5c59-4e26-8c0b-0139fd0a9f81](https://github.com/user-attachments/assets/045871b5-0faa-4e35-afd6-e041e67dcd57)

### If applicable, how would the user interface look like for this enhancement?

Na

### Is there an alternative?

Use giants helper.

### Screenshots

![Uploading 7e37169e-5c59-4e26-8c0b-0139fd0a9f81.jpg…]()

**Comment by Tensuko** [comment]
RCR?

**Comment by Tensuko** [comment]
Don't know what that is in the game....

**Comment by Grantchromeshop** [comment]
It's a map and planter c9nversion.

**Comment by Tensuko** [comment]
???

**Comment by Grantchromeshop** [comment]
Don't worry about it. It's easy enough to use giants. It would be cool if you were able to get ai to ground deform like you have the option for crop destruction.
