### ISSUE TITLE
MP: Sähmaschine läuft nicht ohne Dünger

### ISSUE THREAD

**Issue by Kitekater** [Courseplay/Courseplay_FS25#156]
### Version

8.0.0.2

### Spielversion

1.4.0.0

### SP/MP

MP (Multiplayer)

### Was ist passiert?

Die Sähmaschine lässt sich, trotz deaktivierter Düngefunktion im Menü, nicht betreiben , wenn kein Dünger eingefüllt ist. (Meldung: Sähmaschine auffüllen)
Auch wird der Dünger trotz Deaktivierung verbraucht, falls sich Dünger in der Sähmaschine befindet.
Fehler tritt im SP NICHT auf.

### Wie können wir diesen Fehler nachstellen?

CP-sähen im Multiplayer ohne eingefüllten Dünger

### Was hätte passieren sollen?

Sähmaschine sollte ohne Dünger mit CP laufen

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18263200/log.txt)

### Screenshots

![cp_saehmaschine](https://github.com/user-attachments/assets/c1891437-ed78-4f14-bdee-271ab7c0b8fd)

**Comment by schwiti6190** [comment]
@Kitekater Hello Kitekater, can you try this fix in mp: https://github.com/Courseplay/Courseplay_FS25/pull/198?

**Comment by Kitekater** [comment]
> @Kitekater Hello Kitekater, can you try this fix in mp: #198?

Sorry, doesnt work in MP.
I added the line 25

sowingMachine.lastAIHasSprayed = nil

manually in 
FertilizingSowingMachineController.lua

no difference to before

**Comment by DEKoelle** [comment]
Hallo ich habe V8.0.0.4 in MP die Dünger funktion lässt sich nicht abschalten, wenn Leer ist sagt er das , das Gerät aufgefüllt werden soll, wenn was drin ist an Dünger wird trotz Deaktivierte Dünger funktion, Dünger verwendet
