### ISSUE TITLE
OXBO Geräte fahren nach abladen zu früh los

### ISSUE THREAD

**Issue by Draku1986** [Courseplay/Courseplay_FS25#157]
### Version

8.0.0.2

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Sowohl beim OXBO MKB-4TR (Spinat-Ernter) als auch dem BP2140e (Buschbohnen-Ernter) klappt das entladen nicht sauber.

Beide Geräte heben ihren Bunker beim abladen aus, und wenn er abgebunkert hat, fährt er direkt weiter ohne zu warten das der Bunker wieder unten ist.
Dies hat zur Folge das er ein paar Meter stehen lässt (Siehe Screenshot)

Als Workaround für kleine Felder nutze ich die CP-Funktion "Drescher selbst abtanken) aber je nach Feldgröße und Anhänger standpunkt, funktioniert das nicht immer 

### Wie können wir diesen Fehler nachstellen?

Buschbohnen oder Spinat ernten und abbunkern

### Was hätte passieren sollen?

Bevor er nachdem abbunkern weiterfährt, warten bis der Bunker wieder unten ist.

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18263674/log.txt)

### Screenshots

![Screenshot 2024-12-27 213557](https://github.com/user-attachments/assets/7ea016a0-89be-483c-919d-ff4bfa433e94)
![Screenshot 2024-12-27 220324](https://github.com/user-attachments/assets/0a99da02-6cd2-47cf-8be9-d0365047b3b5)

**Comment by Maestro-Ralf** [comment]
The same problem exists with trailer potato harvester.

**Comment by Tensuko** [comment]
Collecting the problems #176
