### ISSUE TITLE
FS25 unable to recognize Courseplay when installed to "Documents\My Games\FarmingSimulator2025\mods\" folder.

### ISSUE THREAD

**Issue by skibxskatic** [Courseplay/Courseplay_FS25#158]
### Version

8.0.0.2

### SP/MP

SP (Singleplayer)

### What is your question about?

Global CP settings

### What is your question?

I am familiar with installing mods (e.g. copying and pasting the .zip file to the mods folder). Checking the Installed Content in the game and the Control Settings, Courseplay is not a selectable mod to run.

### Screenshots

![image](https://github.com/user-attachments/assets/64577604-2c0f-4bf6-ba76-ff989630e144)

**Comment by Tensuko** [comment]
logfile

**Comment by skibxskatic** [comment]
Figured it out. FS25 wasn't updated to latest version.
