### ISSUE TITLE
Ballensammel Erweiterung Krone Quaderpresser, LUA Error und msg no field found

### ISSUE THREAD

**Issue by Mechalski** [Courseplay/Courseplay_FS25#159]
### Version

8.0.0.2

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

beim Versuch Gras zupressen bzw. zu Häckslen kommt die Fehlermeldung KI -Heelfer XY  hat die Arbeit außerplanmäßig beendet - Kein Feld gefunden. Zudem kommt ein LUA Error 
![Uploading 7314fcf33ac488cf1c771febc50626e8.jpg…]()

### Wie können wir diesen Fehler nachstellen?

Gras Feld Mähen und versuchen zu pressen

### Was hätte passieren sollen?

/

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18263852/log.txt)

### Screenshots

![7314fcf33ac488cf1c771febc50626e8](https://github.com/user-attachments/assets/92a1d7a7-5cf9-4f6f-b9ca-68b30fc839a5)

**Comment by Tensuko** [comment]
Das ist Giants Script.... Und kein Feld gefunden ist eine Giants Nachricht.
Screenshot von der log bringt uns nichts, wäre cool zu sehen was du gemacht hast.

Und kein Problem.
Also kann es nicht CP zuordnen.
![grafik](https://github.com/user-attachments/assets/f2d05988-6da2-4c9d-a5a3-33832e0f0c62)

**Comment by Tensuko** [comment]
You have a few mods that could be the reason it is not working..... Try without mods and only CP.

**Comment by Mechalski** [comment]
Also ich hab das gerade noch mal in einem sauberen Savegame nur mit Courseplay Probiert und den selben Fehler erhalten. 

https://youtu.be/Bh0iseIngGE

**Comment by Tensuko** [comment]
Ja jetzt habe ich auch endlich mal ein Detail.... Und konnte es direkt auch ausprobieren so wie du - es ist der Ballen sammler hinten.

**Comment by FanFSEver** [comment]
I can confirm the same issue with Krone Bigpack 1290 Baler when the collector active. 

I did noticed something interesting.
When I activate the course the first time while starting near the starting point it works fine. However, as soon as I stop and try to restart the route the above error appears. I have been able to replicate this error numerous times in this manner. 

I have also noticed the following:
In the MiniHub the type of course is indicated as CP Fieldwork, however
In the Coursegenerator the type of course is set to CP: BALE COLLECT/WRAP. If you change this to CP FIELDWORK all values are set to default ie. START POINT is reset to FIRST WAYPOINT. If I change this and then try to restart the route which does not work - it resets the course generator to the mentioned settings.

PS. Thank you very much to doing courseplay so quickly. One of my three must have mods to play FS. Will download it from Modhub as soon as you get it on there.

**Comment by RobinHooooood** [comment]
@Tensuko Hab gerade das Update auf 8.0.0.4 runter geladen und getestet. die Lua Errors sind nun weg, allerdings sagt der Helfer, dass der Job erledigt ist, wenn der Ballencollector voll ist und beendet die Arbeit.

**Comment by Tensuko** [comment]
Ja gibt auch dazu schon ein Issue
