### ISSUE TITLE
CP Helfer senkt Werkzeug in erster Reihe nach Vorgewende nicht ab

### ISSUE THREAD

**Issue by Protheus23** [Courseplay/Courseplay_FS25#160]
### Version

8.0.0.2

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Die erste Reihe nach dem Vorgewende wird (mit allen bisher genutzten Werkzeugen) nicht beackert (Wortspiel beabsichtigt).

Getestet mit Pflug, Mähwerk, Wender und Schwader (die Modelle hab ich nicht mehr im Kopf...waren teils gemietet).

### Wie können wir diesen Fehler nachstellen?

Die Fahrzeuge fahren das eingestellte Vorgewende korrekt ab. Danach wird das Werkzeug angehoben und zum Startpunkt der Reihen gefahren. Hier wird die erste Reihe zwar korrekt abgefahren, aber ohne das Werkzeug abzusenken. Beim Reihenwechsel senkt er dann ab der 2. Reihe das Werkzeug ab und arbeitet korrekt.

### Was hätte passieren sollen?

Das Werkzeug hätte abgesenkt werden müssen bevor die erste Reihe abgefahren wird.

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18264012/log.txt)

### Screenshots

hab keinen gemacht (wäre auch schwer zu machen)

**Comment by Tensuko** [comment]
Duplicate #79
