### ISSUE TITLE
Gespeicherte Kurse auf Dedi Server speichern

### ISSUE THREAD

**Issue by StSt1408** [Courseplay/Courseplay_FS25#163]
### Version

8.0.0.2

### SP/MP

MP (Multiplayer)

### Was kann mit deiner Idee gemacht werden?

Courseplay Kurse auf einem Dedi Server so speichern das diese für alle Zugänglich sind.

### Wie könntest du dir vorstellen, wie deine Idee in CP aussehen könnte.

AutoDrive speichert alle Wegpunkte im savegame Ordner

### Gäbe es eine Alternative?

Bin nicht sicher

### Screenshots

-

**Comment by Tensuko** [comment]
Geplant zu einem späteren Zeitpunkt, aktuell nur durch speichern im fahrzueg und andere können sich den dann lokal speichern.
Ordner synchronisieren über ein tool, oder Dateien an die andren Spieler übertragen.
