### ISSUE TITLE
Helfer kann nicht mit MacDon PW8 gestartet werden

### ISSUE THREAD

**Issue by RobinHooooood** [Courseplay/Courseplay_FS25#165]
### Version

8.0.0.2

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Ich wollte mit dem MacDon PW8 die Dreschschwad aufnehmen, deswegen hab ich die Arbeitsbreite angepasst. Nachdem die Arbeitsbreite passend war, habe ich einen Kurs generiert und wollte den Helfer einstellen. Der Helfer ist eingestellt fährt aber nicht die Punkte ab sondern steht an einer Stelle still.

### Wie können wir diesen Fehler nachstellen?

Mit dem MacDon Paket eine Dreschschwad legen, danach mit einem beliegen Drescher die Dreschschwad mithilfe des MacDon PW8 einen Kurs erstellen und den Helfer einstellen.

### Was hätte passieren sollen?

Der Helfer hätte den generierten Kurs abfahren sollen 

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18264481/log.txt)

### Screenshots

![fsScreen_2024_12_28_01_34_53](https://github.com/user-attachments/assets/90466454-d04a-4953-ab9e-080d657c97c3)
![fsScreen_2024_12_28_01_34_55](https://github.com/user-attachments/assets/ceb11c86-9f82-4a46-832f-de796a2f1201)
![fsScreen_2024_12_28_01_35_03](https://github.com/user-attachments/assets/3d4a1310-d9ec-4580-bc99-ef73da77f397)

**Comment by pvaiko** [comment]
Duplicate of #60
