### ISSUE TITLE
CP activates AD, but AD does not activate CP.

### ISSUE THREAD

**Issue by erksartori** [Courseplay/Courseplay_FS25#166]
### Version

8.0.0.2

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

CP activates AD, but AD does not activate CP.

### How can we reproduce this?

I'm harvesting straw, when it's full it leaves the CP and goes to the AD, to make the journey to unload the straw, when it returns it gives a message and doesn't harvest the straw again.

Message: "Driver of 3650: Not able to start AI Helper"

### What did you expect to happen?

Depending on the FS22 version, or earlier, as soon as the tractor returns from transport it starts harvesting from where it left off.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18264608/log.txt)

### Screenshots

![2300320_2](https://github.com/user-attachments/assets/526af3bd-6169-45db-9f65-b1bc4f0c60ee)

**Comment by Resandise** [comment]
This kinda sounds like a AD issues, not a CP.  I could be wrong though.  Did you submit an Issue to AD too?

**Comment by erksartori** [comment]
Not yet, I had forgotten about that detail. I'll do it now.

**Comment by erksartori** [comment]
Now, yes, it's in AD

#41

**Comment by Resandise** [comment]
@erksartori apparently, on AD, if you right click on the wheel, it changes it from Giants Helper to CP.  Try that.

**Comment by erksartori** [comment]
It was explained in AD how to solve this problem, by clicking on the icon as shown in the image in @Resandise answer you change to CP. where the icon will change to CP. Hugs and thank you very much for your attention.
