### ISSUE TITLE
Incorrect Width

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS25#167]
### Version

8.0.0.2

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

Incorrect width calculation for the Pottinger TOP 1403 C.  When folded, it calculates at 2.1m.  When unfolded, and clicked on Work Width, it calculates at 14.1m.  Store page says that it is 14m.  When course is made at 14.1m, it misses a strip in between rows. 

### How can we reproduce this?

Connected the TOP 1403 C to a tractor and generate course

### What did you expect to happen?

It to calculate proper width

### Attach your log.txt!

![fsScreen_2024_12_27_20_05_45](https://github.com/user-attachments/assets/19bcdead-b27f-4e1c-8c16-e5ab923af211)

### Screenshots

![fsScreen_2024_12_27_20_01_56](https://github.com/user-attachments/assets/20353fa0-fb03-454e-bcbb-04a2f01a6c30)
![fsScreen_2024_12_27_20_02_09](https://github.com/user-attachments/assets/97da71b5-31f2-4a1f-a610-3ca7238d38b3)

**Comment by Tensuko** [comment]
Thats what those Buttons are for (can also scroll that number up and down)
![grafik](https://github.com/user-attachments/assets/c8462329-63f7-4e9b-ad39-fa32a39f9fa7)

**Comment by Resandise** [comment]
@Tensuko when using that to adjust the width, then using CTRL+G to generate course, it resets it back to 14.1.

**Comment by Tensuko** [comment]
Ok then we have to check that.

**Comment by Resandise** [comment]
It does generate at the adjusted if using the helper menu and adjusted it in Fieldwork Settings, but not from the GUI
