### ISSUE TITLE
Miete legen mit ÜLW und Aufnahme durch Maus

### ISSUE THREAD

**Issue by JayDi999** [Courseplay/Courseplay_FS25#168]
### Version

8.0.0.2

### SP/MP

MP (Multiplayer)

### Um was geht es bei deiner Frage?

weiteres später

### Wie lautet deine Frage?

Ich glaube es ist kein wirklicher Bug aber evtl. fällt es unter die Kategorie "Verbesserung"

Die Überladewagen für Rüben kippen bei der Erstellung einer Miete die Rüben nicht lange in eine Richtung aber sondern legen die Miete immer breiter ab. So hat man am Ende eine sehr breite Miete aber dafür sehr kurz.

Die Maus hat damit dementsprechend ein Problem bei der Aufnahme weil die Arbeitsbreite von 10,2 Meter nicht für 35 Meter Miete reicht und CP kommt sich beim Abfahren dann in die Quere indem es in die Miete fährt

ich habe zwei Bilder angehängt um zu zeigen wie es beim Abfahren mit dem Überladewagen und dem Abkippen auf dem Feld nach einer Weile aussieht

Danke !

![Miete](https://github.com/user-attachments/assets/843fbc72-571c-4318-aa91-5f101e8d178d)

![Maus](https://github.com/user-attachments/assets/6e95907e-90fb-42b3-91e4-31400f3db250)

**Comment by Tensuko** [comment]
Das Problem mit den ÜLWs kennen wir....
Steht im Grunde hier mit drin als Verbesserung.
#43
