### ISSUE TITLE
Silohelfer Klappt Geräte nicht auf vor nutzung!

### ISSUE THREAD

**Issue by The-Fiesslinger** [Courseplay/Courseplay_FS25#169]
### Version

8.0.0.2

### Spielversion

1.4.0.0

### SP/MP

MP (Multiplayer)

### Was ist passiert?

Der Helfer senkt Schild und Walze ohne davor aufzuklappen bzw. beginnt Arbeit mit Eingeklappten Geräten!
Selbes bei Radlader mit Schiebeschild. Heben und senken funktioniert ohne Probleme. Es spielt auch keine Rolle wie viele Geräte angehängt sind. Er fährt auf die Parkposition bei einem Abfahrer klappt alles zu und hebt es an. Nur beim wieder los fahren will er nicht.

### Wie können wir diesen Fehler nachstellen?

Helfer im Silo schieben lassen.

### Was hätte passieren sollen?

Vor der Helfer Geräte absenkt, Geräte aufklappen 

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18264703/log.txt)

### Screenshots

![Screenshot 2024-12-28 030903](https://github.com/user-attachments/assets/f87fd341-050f-4c44-a204-af9adbcee0b8)
![Screenshot 2024-12-28 030553](https://github.com/user-attachments/assets/48d98df9-6c30-4636-a37c-fe690c995422)
![Screenshot 2024-12-28 030654](https://github.com/user-attachments/assets/6403f1c9-cd23-4211-a22d-9f557bfdabf9)
![Screenshot 2024-12-28 030750](https://github.com/user-attachments/assets/28d1bd34-d5be-47f0-b27d-9cbdc44cbd2c)

**Comment by Tensuko** [comment]
Selber aufklappen dann geht es, eher low priority aber wir gucken bei gelegenheit.
