### ISSUE TITLE
Issue with Center to Headland Transition 

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS25#170]
### Version

8.0.0.2

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

When running a course with TOP 1403 C and followed with a baler (course copied), when transitition from center to headland, it miss the first half of the headland with both windrower and baler.

### How can we reproduce this?

Created course, River Bend map, field 84 with Pottinger TOP 1403 C, starting on center and run it. 

### What did you expect to happen?

It not to skip half a headland

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18264707/log.txt)

### Screenshots

![fsScreen_2024_12_27_20_09_45](https://github.com/user-attachments/assets/2507ab2e-04f8-4981-9501-cdabe16a9e1c)

**Comment by Resandise** [comment]
When transitioning from center to 1st headland with seeder, tractor just took off into the woods.  

[log.txt](https://github.com/user-attachments/files/18265054/log.txt)

**Comment by pvaiko** [comment]
11c6c02 should fix this

**Comment by CaptainRush** [comment]
same issue here with same version.

Whenever the tractor needs to headland to center or from center to headland there is this one node where it almost everytime looses track and just drives straight forward
