### ISSUE TITLE
CP won't start Bale Collect/Wrap

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS25#171]
### Version

8.0.0.2

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

When attempting to start CP Bale Wrapper with Kuhn SW 4014, it gives error "Could not find Path" and stop.  NON-Contract field/bales.  

### How can we reproduce this?

make grass bales, connected wrapper and attempt to wrap bales

### What did you expect to happen?

it to wrap the bales

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18264725/log.txt)
[savegame3.zip](https://github.com/user-attachments/files/18264727/savegame3.zip)

### Screenshots

![fsScreen_2024_12_27_20_23_16](https://github.com/user-attachments/assets/0dcc5023-3238-4baa-936a-b71294c9a83e)

**Comment by Resandise** [comment]
When starting with the start button on hud, it get this error immediately.  When starting it from Create Job menu, it drives a little bit, then opens the wrapper before giving the same error.

**Comment by Resandise** [comment]
Does the same thing when attempting to collect bales with Arcusin FSX 63.72 and the Bale Autoload Ponge SPX 816 (Mod)

![fsScreen_2024_12_27_21_27_09](https://github.com/user-attachments/assets/48c8500d-ebc0-422a-9ca0-bacf40cb8a66)
[Uploading log.txt…]()

**Comment by Resandise** [comment]
may be connected with issue #159

**Comment by pvaiko** [comment]
11c6c02 should fix this.
