### ISSUE TITLE
Spreader stop work - vechicle off track

### ISSUE THREAD

**Issue by krookoo** [Courseplay/Courseplay_FS25#172]
### Version

8.0.0.2

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

JD R7 with AMAZONE UX5201 40m after make circle off track.

### How can we reproduce this?

Make course on merged fields 40, 41, 48, 49 on Zielonka.
In options set sharpening the corners of the headlands and Rounding the corners 0.

### What did you expect to happen?

Spreader continue fieldwork.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18264728/log.txt)

### Screenshots

![fsScreen_2024_12_28_03_16_55](https://github.com/user-attachments/assets/2df870c6-a189-4c2d-88ca-de7a8d4c1920)
![fsScreen_2024_12_28_03_17_23](https://github.com/user-attachments/assets/cd865ae0-9c07-4e96-9c8c-720479494c84)
![fsScreen_2024_12_28_03_18_26](https://github.com/user-attachments/assets/46627116-93f8-4ebe-a54a-ddd656ac80cc)
![fsScreen_2024_12_28_03_18_28](https://github.com/user-attachments/assets/dc0b3797-3a7e-4337-9b64-c3e2e313ee21)

**Comment by Tensuko** [comment]
#79

**Comment by krookoo** [comment]
In 8.0.0.3 problem still persist.

**Comment by Tensuko** [comment]
Then we need a logfile with debug in vehicle settings active.

**Comment by krookoo** [comment]
[log.txt](https://github.com/user-attachments/files/18270255/log.txt)
https://youtu.be/DncZilmYJ4A
From start i deleted course generated on 8.0.0.2 and create new one.
I start course from end of cricle for faster show problem.

**Comment by krookoo** [comment]
Have you checked the previous log and video?
When i generate same course in 8.0.0.4 spreader continue work.
He left only corner (screen)
![fsScreen_2025_01_01_15_05_42](https://github.com/user-attachments/assets/a3e81766-0655-4fc8-ab46-f00e381ee547)

**Comment by krookoo** [comment]
I create new game on Zielonka, and bug again exist.
Maybe you need to open again this topic?
![fsScreen_2025_01_01_17_11_01](https://github.com/user-attachments/assets/b146fc8f-d68b-49e5-bfd7-f675ea600a17)
