### ISSUE TITLE
Caff shredding

### ISSUE THREAD

**Issue by Woodshock** [Courseplay/Courseplay_FS25#175]
### Version

8.0.0.2

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

So I set the Jaguar 990 on the field created a course set up a loader copy set up everything nice and fine and doing its job fantastic it was some figuring out but I was amazed how well it work but now the issue here is as you can see in the picture One more thing to I want to suggest for future implement let the tool on while turning the Axion 990 because now shut off tool its turning and the loader also have to turn and their is also an issue its get blocked by the Jaguar 990 and then its say no course found you have to go to loader again and press play again because yes he fix the issue be driving backwards and then the error occurs by not finding the course anymore so I include a picture when the tractor needs to turn but the Jaguar will not work because its not in position so the Jaguar needs to keep working so the tractor can pull behind like in real life 

### How can we reproduce this?

Set up Axion 990 and a loader with a tralier

### What did you expect to happen?

that it will keep going 

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18265921/log.txt)

### Screenshots

![chaff](https://github.com/user-attachments/assets/e717ca0d-3d37-4357-95a7-93e4f170f419)
![caff 2](https://github.com/user-attachments/assets/ca344d4c-ed22-425c-ad6b-a452c4ec8519)

**Comment by Tensuko** [comment]
Without Headland there its impossible.
Turn off motor is not a problem.
Your text without any dot and comma is almost unreadable....
