### ISSUE TITLE
Gras Häckseln

### ISSUE THREAD

**Issue by Mechalski** [Courseplay/Courseplay_FS25#177]
### Version

8.0.0.2

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Beim Versuch ein gemähtes Gras Feld zu Häckseln LUA Error und Häcksler fährt nicht los bzw. aktiviert die Gerätschaft. Geht auch nicht im Sauberen Savegame (nur Courseplay)

### Wie können wir diesen Fehler nachstellen?

Versuchen mit dem Kurs des Mähers ein Feld zu häckseln

### Was hätte passieren sollen?

/

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18265972/log.txt)

### Screenshots

![7062cf52404bafac334dd8d056422cd3](https://github.com/user-attachments/assets/e5e3e1ca-80cf-4195-89f1-64e65055a249)

**Comment by Tensuko** [comment]
Duplicate, fixed in next Release.
