### ISSUE TITLE
Harvester says needs to unload 

### ISSUE THREAD

**Issue by Woodshock** [Courseplay/Courseplay_FS25#179]
### Version

8.0.0.2

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

AI helper keeps saying he needs to be unloaded, and yes I set the Headlands now.

### How can we reproduce this?

Set up like I do 

### What did you expect to happen?

Smooth working 

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18266287/log.txt)

### Screenshots

![caff3](https://github.com/user-attachments/assets/4f51279c-d283-4b27-a83d-7bf0ec1b3bb4)

**Comment by Woodshock** [comment]
I just read the manual for now it does not work with choppers that's sad

**Comment by Tensuko** [comment]
Where does it say it doesn't work with choppers?

**Comment by Woodshock** [comment]
![unload](https://github.com/user-attachments/assets/217e4d2f-6c03-46d9-b2a5-a31963dbe81d)

**Comment by Woodshock** [comment]
The Jaguar 990 is set up with headlands, I start the Jaguar up and set the tractor and a loader with copy course, but the Jaguar keeps saying it constantly needs to unload.
![caff3](https://github.com/user-attachments/assets/11eefe9d-dbf4-4572-9697-ab3195ef016f)

**Comment by Tensuko** [comment]
We have to update the help then.
Can't tell you right now why it does not unload into the trailer.
Must check this, on my savegames it works.

**Comment by Woodshock** [comment]
It will unload but it keeps lagging because it constantly says the harvester is full do I have the wrong setting on the Jaguar perhaps?

**Comment by Tensuko** [comment]
I will have to check that later... can't do right now.

**Comment by Woodshock** [comment]
I found the problem, as you see the Jaguar has a capacity of 37 liters so an unloader can be set up, now as you see the lowest unload setting is at 40% maybe tweaking that will do it? 
![tank Jaguar](https://github.com/user-attachments/assets/bdf97523-46e8-4017-be5d-4a6d670bf4ae)
![unload](https://github.com/user-attachments/assets/7fe01767-cac6-4800-927b-3cc441146df9)

**Comment by regs1980** [comment]
37l This is the capacity of the silage additive tank.

**Comment by Woodshock** [comment]
So why is it doing this?

**Comment by Woodshock** [comment]
If I put a longer pipe on it will that do it maybe that's the problem I will try this because I set the chopper up with a short pipe for a loader behind it.

**Comment by Woodshock** [comment]
nope still no solution

**Comment by Tensuko** [comment]
Patient is the key...

**Comment by Woodshock** [comment]
Yes I mean the solution on the Jaguar to change it to a longer pipe
