### ISSUE TITLE
Häcksler beginnt nicht mit der Arbeit

### ISSUE THREAD

**Issue by nils1981-spass** [Courseplay/Courseplay_FS25#182]
### Version

8.0.0.2

### SP/MP

SP (Singleplayer)

### Um was geht es bei deiner Frage?

Fahrzeug Einstellungen

### Wie lautet deine Frage?

Moin Zusammen, habe heute versucht mit dem Maishäcksler Gras zu häckseln. Der Häcksler fährt auch mit Autodrive zum Feld, Motor an alles läuft nur er geht nicht in Arbeitsstellung jedesmal wenn ich in ausschalte und neu starte immer das selbe.

**Comment by Tensuko** [comment]
Mit dem Pick-Up oder womit?

**Comment by regs1980** [comment]
Das kann nur die Pickups sein, der Krone XDisc 620 und der Claas Direct Disc 500 funktionieren sehr gut.

**Comment by nils1981-spass** [comment]
Ja mit dem Claas Pick-UP den klappt er nicht aus auch das Rohr am Claas Häcksler wird dabei nicht ausgefahren

**Comment by nils1981-spass** [comment]
wenn ich selber fahre geht es aber nicht mit Coursplay 


[IMG_8270](https://github.com/user-attachments/assets/7ca9aa7e-6938-49c4-b58b-bede1089120e)
 
![IMG_8269](https://github.com/user-attachments/assets/ea0356a7-e941-4939-b263-177b28d04f04)

**Comment by Tensuko** [comment]
Neue Version laden da ist pickup gefixt

**Comment by nils1981-spass** [comment]
Habe ich gemacht funktioniert, nur es werden nun noch die Koordinaten oder so angezeigt vor und hinter dem Häcksler

**Comment by Tensuko** [comment]
Huch?
Trotz debug aus?

**Comment by nils1981-spass** [comment]
Ok ich schaue nochmal nach ob das debug an geschaltet ist. sonst melde ich mich wieder

**Comment by nils1981-spass** [comment]
Fehler gefunden debug war aktiviert nach dem ich deaktiviert habe sind die Punkte und Linien nicht mehr sichtbar. Danke nochmal
