### ISSUE TITLE
Hide Debug Waypoints in Menus

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS25#186]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

When vehicle debug is on, and course running, the vehicle debug waypoints over lap into the menus

### How can we reproduce this?

Run course with vehicle debug on, then go into a menu

### What did you expect to happen?

waypoints hidden

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18266812/log.txt)

### Screenshots

![fsScreen_2024_12_28_10_33_27](https://github.com/user-attachments/assets/c88fdea1-8b39-402b-a9c6-7e13dc452b05)

**Comment by Tensuko** [comment]
Won't fix.
It is debug....
