### ISSUE TITLE
Vine tractor getting stuck

### ISSUE THREAD

**Issue by Universeal13** [Courseplay/Courseplay_FS25#187]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

If the vines are not straight the tractor at the end of the vine when it tries to got to the next one is getting stuck in the vine

### How can we reproduce this?

add multiple vines. one short and one long. I did this in zielonka map field 93

### What did you expect to happen?

ai is getting stuck when it tries to turn

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18266918/log.txt)

### Screenshots

![fsScreen_2024_12_28_19_18_27](https://github.com/user-attachments/assets/0bc688db-9919-48eb-9258-fe4a07b66f19)

**Comment by Tensuko** [comment]
Yeah thats a problem of the turn, I found while testing something else.

**Comment by Universeal13** [comment]
Now it doesn't know where to stop
![fsScreen_2025_01_01_12_39_26](https://github.com/user-attachments/assets/69d45469-0d8c-4c6c-a67d-7e83dcf571b2)
