### ISSUE TITLE
MacDon special header PW8 harvest issue

### ISSUE THREAD

**Issue by VjPetrovic** [Courseplay/Courseplay_FS25#189]
### Version

8.0.0.2

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

When is MacDon special header attached on ordinary harvester CP won't start playing. The course is saved and loaded properly.
The course is created for MacDon havester and loaded to ordinary harvester (CLAAS or FENDT). Wen the course is started, nothing happend.

### How can we reproduce this?

Create harvest course for MacDon and save it. Conect special MacDon header PW8 on any harvester, load the saved course and start the course.

### What did you expect to happen?

Loaded course will had to work.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18267405/log.txt)

### Screenshots

![Snimka zaslona 2024-12-28 202732](https://github.com/user-attachments/assets/02b1957d-418d-424f-98ae-3b8e0f0b5606)

**Comment by Tensuko** [comment]
https://github.com/Courseplay/Courseplay_FS25/wiki

"Always update to the latest build and check if the problem really still exists before reporting issues."

https://github.com/Courseplay/Courseplay_FS25/releases

**Comment by VjPetrovic** [comment]
thanks
I saw it just after I send it
my mistake

**Comment by Tensuko** [comment]
No Problem :)
