### ISSUE TITLE
Settings auf Multiplayer Server

### ISSUE THREAD

**Issue by Justice-Molton** [Courseplay/Courseplay_FS25#190]
### Version

8.0.0.3

### SP/MP

MP/ Multiplayer

### Um was geht es bei deiner Frage?

Kurserstellung

### Wie lautet deine Frage?

Ist es gewollt, das jeder alle Einstellungen ändern kann? 
Weil Dinge wie Kosten vom  Fahrer und Reparatur settings etc. Sollten doch nur vom Admin einstellbar sein. 
Bei uns sind aber von allen, alle eistellungen machbar.

**Comment by Tensuko** [comment]
Ist absicht, wenn man Mitspieler hat denen man nicht trauen kann, ist es sehr schade.
