### ISSUE TITLE
Swather Issue: Combine won't start to pick up swath

### ISSUE THREAD

**Issue by Ouedzets** [Courseplay/Courseplay_FS25#191]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

The combine won't to pick up the oats swath. I copied the course from the MacDon Swather and also created a new one from scratch for the combine  
When I press start, the Case Axial Flow 7150 combine starts but does not move forward.

### How can we reproduce this?

On riverbend spring, 
Use Case Axial Flow 7150 and MacDon PW8
See attached pictures

### What did you expect to happen?

That the combine picks up the swath...

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18267616/log.txt)

### Screenshots

![20241228210438_1](https://github.com/user-attachments/assets/af108fd0-9f04-4518-9f4e-c6e59478e015)
![20241228210500_1](https://github.com/user-attachments/assets/469465c6-2b50-4912-9fda-548d7ddbb524)
![20241228210610_1](https://github.com/user-attachments/assets/0957babc-5feb-49ec-9991-c827a1a633b9)
![20241228211139_1](https://github.com/user-attachments/assets/a8cf1f0e-81fa-4ea5-b420-1454430bfaa8)

**Comment by Tensuko** [comment]
Available mod:  (Version: 8.0.0.2) FS25_Courseplay
Warning: Only zip mods are supported in multiplayer. You need to zip the mod FS25_Courseplay to use it in multiplayer.

Old Version.....

**Comment by Ouedzets** [comment]
Hello, thanks for the answer. 
I'm playing SP and I installed 8.0.0.3 which came out 6hr ago.
And it's working perfectly now!
Great thanks!
And in the future I will check for the newest versions... before bothering you...
Thanks again, you guys are doing a tremendous !
