### ISSUE TITLE
Harvester mit Mac Don PW8 startet nicht mit CP

### ISSUE THREAD

**Issue by Dethstroke** [Courseplay/Courseplay_FS25#192]
### Version

8.0.0.3

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Nach dem Schwadmähen mit dem Mac Don und dem kopieren des Kurses in einen normalen Drescher mit MacDon PW8 bleibt der Drescher einfach stehen und fährt nicht los egal an welchen Wegpunkt man ihn setzt. Das Haferschwad bleibt einfach liegen.

### Wie können wir diesen Fehler nachstellen?

Getreide auf Schwad mähen und versuchen es von einem normalen Drescher mit dem Pw8 dreschen zu lassen. 

### Was hätte passieren sollen?

Der CP Fahrer hätte das Schwad dreschen sollen. 

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18267680/log.txt)

### Screenshots

![Unbenannt](https://github.com/user-attachments/assets/c8c8e04b-06e0-494a-acaf-8670ce9fe650)

**Comment by Tensuko** [comment]
(Version: 8.0.0.0) FS25_Courseplay

![grafik](https://github.com/user-attachments/assets/647869d9-ae37-4cb0-bbd7-6ff8d5e59d2c)

Ur alte Version..... Immer erste die neueste laden bevor man ein Issue auf macht.

https://github.com/Courseplay/Courseplay_FS25/releases
