### ISSUE TITLE
Potato Seeder when reversing 

### ISSUE THREAD

**Issue by RockSteadyRedBull33** [Courseplay/Courseplay_FS25#193]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

Tractor when reversing turns the steering left, right over and over at 1mph to position for next row this happens everytime regardless of field and tractor 

### How can we reproduce this?

use tractor and potato seeder 

### What did you expect to happen?

reverse smoothly at pre set speed (5.6mph)

### Attach your log.txt!

unknown

### Screenshots

![20241228212406_1](https://github.com/user-attachments/assets/79f30b9f-7f57-4140-9965-38cb67464c65)
![20241228212406_2](https://github.com/user-attachments/assets/d1bb3b25-41e5-4e73-8f23-2eac47fbd2f6)
![20241228212407_1](https://github.com/user-attachments/assets/062b67de-b7af-4a5b-bdf5-7ac3978a4e5b)
![20241228212407_2](https://github.com/user-attachments/assets/9f368bd3-0b28-474c-9016-6a727f286739)
![20241228212408_1](https://github.com/user-attachments/assets/00998cfd-ce65-4103-9713-b80ffe5ead16)

**Comment by Tensuko** [comment]
No log, no help.

**Comment by RockSteadyRedBull33** [comment]
i dont know what a "log" is so cant tag it

**Comment by Tensuko** [comment]
![grafik](https://github.com/user-attachments/assets/b8f1ed2c-2ca9-4b0d-9a71-1ab2116cb0eb)
from 
![grafik](https://github.com/user-attachments/assets/3a8d5035-e6d2-4a23-b115-1a1f04bd4832)
Like written there....
![grafik](https://github.com/user-attachments/assets/20dac952-d367-4dc6-9bd6-3668f901fadb)
