### ISSUE TITLE
Turning and backward speed

### ISSUE THREAD

**Issue by Universeal13** [Courseplay/Courseplay_FS25#194]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

On turning the driver is very slow and on backward is maximum 5km/h

### How can we reproduce this?

any  field that needs turning, sharp turning

### What did you expect to happen?

on f22 you can choose the driver speed. the game ai has greater speed. 

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18267801/log.txt)

### Screenshots

![fsScreen_2024_12_28_23_45_54](https://github.com/user-attachments/assets/161c8f87-cd02-4288-bad1-9ea4e3651e9f)

**Comment by Tensuko** [comment]
The speed can throw off the turn.
Every speed can be changed in the vehicle settings.
If it doesn't go higher, it have its reasons.
We don't care if Giants does it faster, you can use Giants helper then.

To be honest, the fact that a Helper does something and I can do something else is the biggest time saver you can have, you if you watch the helper and got nothing else to do, you can even do it on your own and be faster if you want it so.

Conclusion: Vehicle Settings -> Speeds adjustments on your own risk.

Nothing else will be changed.

**Comment by Universeal13** [comment]
Now it doesn't know where to stop
![fsScreen_2025_01_01_12_39_26](https://github.com/user-attachments/assets/d6ee323f-e45e-416a-a0dc-060af4d89ddf)

**Comment by Universeal13** [comment]
there is no speed in vehicle settings

**Comment by Tensuko** [comment]
Turn on expert mode....
