### ISSUE TITLE
CoursePlay 8.0.0.2 Log?

### ISSUE THREAD

**Issue by CoderKen-ui** [Courseplay/Courseplay_FS25#201]
### Version

8.0.0.3

### SP/MP

SP (Singleplayer)

### What is your question about?

Course creation

### What is your question?

Where is the log stored?  I got an error while trying generate field work course, said could not generate course. The log may have more information.  
Map: Zielonka
Field 72 
Vehicle: McCormick X8.631 VT-Drive
Implement: Samasz Z2-849 H
Field was full of straw from oat harvest 

### Screenshots

![CP_8002_Zielonka_72_could not generate course](https://github.com/user-attachments/assets/f7ab7943-b656-4092-9add-0ab1f9aff480)

**Comment by CoderKen-ui** [comment]
FYI: just updated to 8.0.0.3, problem still exists

**Comment by Tensuko** [comment]
It is always the log.txt from the game.
What generator settings did you use there?

**Comment by Tensuko** [comment]
As always, when can't generate a course, something is wrong with the field or you have to change settings.
