### ISSUE TITLE
Sometimes the character "T" get's automatically changed to "#"

### ISSUE THREAD

**Issue by gslamkov** [Courseplay/Courseplay_FS25#202]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

I tried to save multiple courses for cultivating various fields, and I named them `Cultivation <number of field>` in a folder named "Cultivation".
In both the saved course, and created folder the `T` character in `Cultivation` was changed to `#`, so the word looks like this: `Cultiva#ion`.
For some reason, the first T is not changed.

### How can we reproduce this?

Generate a course, save it, and enter `Cultivation <number>` as the 'Course name'. I've been continuously been reproducing it this way.

### What did you expect to happen?

For the character not to be automatically changed to something else.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18268611/log.txt)

### Screenshots

![Screenshot 2024-12-26 115503](https://github.com/user-attachments/assets/c550f7a1-f292-4c2b-a706-4d3bd282db24)

**Comment by malmi** [comment]
I have the same issue without Courseplay. If you want to rename anything in the game, like a factory, i get the same behaviour.

**Comment by Tensuko** [comment]
Oh, thats good to know, thank you!
So this isn't even a CP Problem....

**Comment by Tensuko** [comment]
Game bug, won't fix.
