### ISSUE TITLE
Rice planter worker stops unexpectedly when run in up/down, no headlands. 

### ISSUE THREAD

**Issue by skibxskatic** [Courseplay/Courseplay_FS25#203]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

When running the rice planter in an up/down, no headland course, when worker reaches the end of a row, the worker stops unexpectedly even when the vehicle settings are set to raise tool early, lower tool late. I'm not sure if this is just a limitation with how GIANTS has built their rice planting logic or if there is a way around planting up/down without headlands with a worker and it's not posted in the HELP section of Courseplay within FS25.

### How can we reproduce this?

Run the rice planter in up/down, no headlands. Once the worker reaches the end, the worker stops unexpectedly and you get the Giants errors as screenshotted. 

### What did you expect to happen?

When the planter reaches the end of the row, lift planter, start at new row, lower planter, continue planting, respecting all GIANT boundaries of a rice field and to lower the planter in the water as expected to keep the worker working.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18268710/log.txt)

### Screenshots

![image](https://github.com/user-attachments/assets/c351cdf5-7a39-4c49-9747-d0a9fc26c80b)

![image](https://github.com/user-attachments/assets/6b01d42d-943f-4b07-87ea-462cb10e9fd2)

**Comment by skibxskatic** [comment]
For testing sake, same thing will happen when sharp corners are turned on and a worker tries to lower the planter after the reposition when the reposition end point is just outside of the rice field or outside of the detected water boundary.

**Comment by Roby1164** [comment]
For rice fields, it is recommended to set the field margin, in the field settings, to 0.8/1, to avoid the helper stopping, near right-angled turns, and also planting outside the flooded part, especially for unsquared fields.

**Comment by Tensuko** [comment]
You should also always use at least one headland!

**Comment by skibxskatic** [comment]
Thanks, this info helps. I'll close this. Is it worth adding this as its own page in the Courseplay In-game Help?
