### ISSUE TITLE
What is the setting to allow a worker to use the loaded/filled implement vs deducting cash while a worker is working?

### ISSUE THREAD

**Issue by skibxskatic** [Courseplay/Courseplay_FS25#204]
### Version

8.0.0.3

### SP/MP

SP (Singleplayer)

### What is your question about?

Course creation

### What is your question?

What is the setting to allow a worker to use the loaded/filled implement vs deducting cash while a worker is working?

### Screenshots

N/A

**Comment by Tensuko** [comment]
It is a basegame setting..... got nothing to with CP.
Game setting buy XY. Check it out.
