### ISSUE TITLE
Field course like a spider web

### ISSUE THREAD

**Issue by Brax-bit** [Courseplay/Courseplay_FS25#206]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

I tried to generate a course für field 4 in the base game Zilonka map with my tractor AGCO 8510 and attached Pöttinger Rotocare V 12400. The generated course looks like a spider web.
![2300320_625](https://github.com/user-attachments/assets/16df4537-6487-4bf2-aed7-ca07c0f7eaab)

### How can we reproduce this?

I use the german language in FS25 so I hope you can find the options.
Try to generate a course for field 4 in the base game Zilonka map with the option "Bahnenform anhand Feldkante" activated ('Rows follow field edge curve'?) and at least 1 headland. You can find this option in 'Feldarbeit Einstellungen' ('fieldwork settings'?)
In my case I used a AGCO 8510 with attached Pöttinger Rotocare V 12400.
![2300320_626](https://github.com/user-attachments/assets/86dc6860-bf15-4641-8ff0-9f3135681136)

### What did you expect to happen?

Generate a normal/ clear course like Courseplay do without this option activated.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18268910/log.txt)

### Screenshots

Screenshots see above

**Comment by Brax-bit** [comment]
In the screenshot I used a John Deere 7810 from a mod but I started the game without any mod except Courseplay 8.0.0.3 and used a basegame tractor AGCO 8510 with the same result.

**Comment by Tensuko** [comment]
That is an experimental  feature and also written in the help menu that, if the course is not working, it will not work and you hafve to turn it off.
Won't fix, please read the manual ingame.
