### ISSUE TITLE
Modified Harvesters Unload trigger to early

### ISSUE THREAD

**Issue by kevanaustin** [Courseplay/Courseplay_FS25#207]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

I'm using a modded harvester with extra storage capacity. The 'Need unloading trigger' is defaulting to un-modded value so it stops and asks for unload even only 20% full.

### How can we reproduce this?

Mod harvester is New Holland CR11 v1.8, also Multifruit Silos in use.

### What did you expect to happen?

Keep going until full

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18268938/log.txt)

### Screenshots

N/a

**Comment by Tensuko** [comment]
Mod Issue, won't fix.
