### ISSUE TITLE
1. Feldbahn wird übersprungen vom Helfer

### ISSUE THREAD

**Issue by dw7109** [Courseplay/Courseplay_FS25#210]
### Version

8.0.0.3

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Es wurden Kurse erstellt mit 2 oder 3 Vorgewenden, Feldmitte im Modus "hoch/runter". Felder wurden manuell vergrößert vor der Kurserstellung. Das wird auch alles richtig erkannt. Angezeigte Bahnen sehen soweit i.O. aus. Wenn ich dieses Feld jetzt bearbeite wird zuerst das Vorgewende bearbeitet (wie eingestellt) die 1. Feldbahn dann aber ausgelassen bzw. der Helfer fährt mit nicht abgesenktem Gerät über die Bahn. Ab der 2. Bahn läuft dann wieder alles wie es soll. Das passiert bei mir aktuell mit der Samasz-Mähwerk-Kombination (vorn und hinten ->9,4m) als auch mit der Grünlandwalze Dalbo Maxiroll 6,4m

### Wie können wir diesen Fehler nachstellen?

Auf der Riverbend Feld 2 die Ränder etwas verbreitern, Gras säen und dann mit den beschriebenen Geräten und den beschriebenen Einstellungen bearbeiten. Das passiert aber auf allen Feldern in diesem Spielstand.

### Was hätte passieren sollen?

Zu erwarten war das das Vorgewende bearbeitet wird und danach die Feldbahnen, beginnend bei der ersten.

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18269164/log.txt)

### Screenshots

![Screenshot 2024-12-29 112831](https://github.com/user-attachments/assets/66ec056d-5198-466b-87c9-fb5ac2e1128d)
![Screenshot 2024-12-29 114015](https://github.com/user-attachments/assets/60e1af86-8938-4c93-adc8-2a3c2ad7d365)

**Comment by Tensuko** [comment]
(Version: 8.0.0.2) FS25_Courseplay
You are not on latest Version.
