### ISSUE TITLE
Ich kann Courseplay nicht starten

### ISSUE THREAD

**Issue by Toaogurch** [Courseplay/Courseplay_FS25#213]
### Version

8.0.0.3

### SP/MP

SP (Singleplayer)

### Um was geht es bei deiner Frage?

Globale CP Einstellungen

### Wie lautet deine Frage?

Hallo zusammen,
ich glaube ich habe bei der Installation von Courseplay FS25 alles richtig gemacht. Ich habe Courseplay in den MOD Ordner geschoben. Dann habe ich das Spiel gestartet und oben rechts ist ein grüner Balken auf dem Courseplay steht. Ich spiele auf einem iMac und drücke dann die Tasten Kombination Control + G oder Command +G aber Courseplay startet nicht!
Was mache ich falsch

![IMG_0511](https://github.com/user-attachments/assets/03098f71-34dc-4ced-b5c4-73677d93ed88)

### Screenshots

![IMG_0511](https://github.com/user-attachments/assets/d12a2846-1d84-490a-ae34-2ea40a47471a)

**Comment by BenniHeid** [comment]
Hast du schon die Rechte Maustaste gedrückt, damit überhaupt die CP-GUI erscheint?

**Comment by Toaogurch** [comment]
Das hatte ich nicht gemacht!!! Ich danke Dir sehr das kannte ich noch nicht!
Mercy und ein gesundes, tolles und friedliches 2025 wünsche ich Dir!!!!
