### ISSUE TITLE
Spinaternter fehlerhaftes Vewrhalten

### ISSUE THREAD

**Issue by AstraThomas** [Courseplay/Courseplay_FS25#214]
### Version

8.0.0.3

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Ich habe einen kurs mit dem Spinaternter erzeugt. Dieser Fährt auch alles ab. Problem wenn er voll ist komm über ad der Abfahrer und Tankt ihn ab. Jetzt müsste der CP-Spinaternter warten bis er wieder Eingeklappt ist damit er weiter ernten kann. Leider fährt CP weiter seinen kurs, wartet nicht und klappt dabei ein. und erst wenn der Spinaternter eingeklappt ist wird wieder richtig geerntet, 

Die Funktion Ernter bleibt beim Abtanken stehen funktioniert auch nicht da es ja das Einklappen des Ernters ist worauf nicht gewartet wird,

### Wie können wir diesen Fehler nachstellen?

Spinatfeld, der Spinaternter und nen Ad Abfahrer. 

### Was hätte passieren sollen?

Der Spinaternter sollte nach dem Abladen Warten bis er Eingeklappt ist

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18269745/log.txt)

Glaube die brauch man hier nicht

### Screenshots

![fsScreen_2024_12_29_14_35_38](https://github.com/user-attachments/assets/10806258-4f26-4833-a78e-17433c641b29)

**Comment by Tensuko** [comment]
Fixed on next release.
