### ISSUE TITLE
3440*1440 

### ISSUE THREAD

**Issue by G9nrikh** [Courseplay/Courseplay_FS25#216]
### Version

8.0.0.3

### SP/MP

SP (Singleplayer)

### What is your question about?

more later

### What is your question?

text "courseplay" incorrect place with 3440*1440 width, it in the middle of screen

### Screenshots

https://i.imgur.com/Nwjxdbr.jpeg

**Comment by Tensuko** [comment]
Duplicate.

**Comment by Tensuko** [comment]
And if you talk about that we nfo panel, you can move it.
