### ISSUE TITLE
Courseplay Editor

### ISSUE THREAD

**Issue by prawler74** [Courseplay/Courseplay_FS25#218]
### Version

8.0.0.3

### SP/MP

MP (Multiplayer)

### What is your question about?

more later

### What is your question?

Hi.
 
First of all. A huge thanx to all developers of this exelent mod. You guys are awesom.
So, to the question. Where do i find the course editor? Or is it not been implemented yet.

Bjørn

### Screenshots

![fsScreen_2024_12_29_17_49_24](https://github.com/user-attachments/assets/40179b13-5e82-4e66-8b12-fb9b56f6be51)

**Comment by Tensuko** [comment]
As written in the changelog for first version, it comes back later.
