### ISSUE TITLE
error while trying to change field for bale wraping

### ISSUE THREAD

**Issue by iAlreadyExist** [Courseplay/Courseplay_FS25#219]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

hello i tried to change field for bale wraping from one field to another and this happend
it was giving me this error and the ai worker was going to the previous field even tho that i have sellected the other field.

### How can we reproduce this?

i dont know how it happend after restarting the game it was fine so i can`t reproduce

### What did you expect to happen?

maybe fix the error

### Attach your log.txt!

2024-12-29 18:48 Error: Running LUA method 'update'.
dataS/scripts/field/course/FieldCourseSettings.lua:362: attempt to perform arithmetic (unm) on nil

### Screenshots

![{913DBFAA-151C-4B68-912A-39E8AF073507}](https://github.com/user-attachments/assets/835aeef0-b883-4dd6-9f02-2f6fe6e13b36)

**Comment by Tensuko** [comment]
No log, no help.

**Comment by iAlreadyExist** [comment]
[log.txt](https://github.com/user-attachments/files/18270374/log.txt)

**Comment by Tensuko** [comment]
#221

**Comment by iAlreadyExist** [comment]
@Tensuko i don`t understand mate why did you close my both topics you wanted log i added on second topic becouse you closed this one.
