### ISSUE TITLE
Silo Tools Fold Closed Before Work

### ISSUE THREAD

**Issue by proactivepcc** [Courseplay/Courseplay_FS25#220]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

MP (Multiplayer)

### What happened?

So far tried with the MES 400 Leveler and the Stego 485 Pro compactor.  Both tools fold closed before work if I have them open.  If they are closed, they stay closed.

### How can we reproduce this?

These were tried at the Biogas plant bunkers on Riverbend map.  I own 6 different tractors and it's happening on all of them.  Doesn't matter if I put them forward or reverse.

### What did you expect to happen?

Expeceted tools to unfold.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18270340/log.txt)

### Screenshots

![screenshot](https://github.com/user-attachments/assets/bd769b4f-8b14-4879-8ab7-53dfd3984ee8)

**Comment by Tensuko** [comment]
Fixed on next release, duplicate issue.
