### ISSUE TITLE
AI doesn't plow all the way

### ISSUE THREAD

**Issue by Tuna-piano** [Courseplay/Courseplay_FS25#228]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

when the AI is plowing a field it does not go all the way to the edge of the field before it stops to turn around. it leaves gaps every time it stops to turn around to start a new path.

### How can we reproduce this?

plow a field with AI

### What did you expect to happen?

AI to completely plow a field.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18271384/log.txt)

### Screenshots

![2300320_5](https://github.com/user-attachments/assets/b4780c2f-8fd0-492a-b087-8c710909f26d)

**Comment by Tensuko** [comment]
Does not look like a plow, but anyway - set raise tool to late (and maybe lower tool to early) in vehicle settings.
