### ISSUE TITLE
I never had that happen in SP, that is super strange....

### ISSUE THREAD

**Issue by Zottelluk** [Courseplay/Courseplay_FS25#229]
I never had that happen in SP, that is super strange....
Any Idea what you did before?

_Originally posted by @Tensuko in https://github.com/Courseplay/Courseplay_FS25/issues/227#issuecomment-2564929042_

**Comment by Zottelluk** [comment]
Eigentlich habe ich nichts besonderes gemacht, ich glaube zeitgleich ein anderes Feld gegrubbert.

**Comment by Valamen** [comment]
I have the same isse.
Updated to 8.0.0.3 yesterday (dident play)
Today i created various folders (Ploughing, Fertilizing, Lime, roll) and moved track into those.
Now trying to save a new couse i get asked for a password.
