### ISSUE TITLE
Wrong Workwidth

### ISSUE THREAD

**Issue by Woodshock** [Courseplay/Courseplay_FS25#232]
### Version

8.0.0.3

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

Automatic Workwidth does not work with the implement 

### How can we reproduce this?

Attaching the implement does not set Workwidth even clicking on it 

### What did you expect to happen?

Auto adjust Workwidth 

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18273564/log.txt)

### Screenshots

![werkbreedte](https://github.com/user-attachments/assets/44a59b96-e001-41c3-821a-ce862b53f659)
![Samasz xt 390](https://github.com/user-attachments/assets/a665ef3a-3fc7-42ff-9459-f1b7f76dcd5b)

**Comment by Tensuko** [comment]
You can adjust this yourself!
Thats what the buttons are for.
Some tools can also be only detected when unfolded.

**Comment by Woodshock** [comment]
yes It did when it unfolded Sorry but so far your team made my QOL on this game bearable hahaha
