### ISSUE TITLE
Helfer nach Laden des Spielstandes wieder starten

### ISSUE THREAD

**Issue by kaffeebart** [Courseplay/Courseplay_FS25#235]
### Version

8.0.0.3

### SP/MP

SP (Singleplayer)

### Was kann mit deiner Idee gemacht werden?

Hallo
der Giants Helfer startet mittlerweile alle aktiven Helfer nach dem laden eines Spielstandes automatisch. 
Ist dieses Feature auch für AD / CP möglich? 
Oder gibt es das schon man muss nur irgendeine Einstellung aktivieren? 

Vielen Dank für eure grossartige Arbeit und die viele Mühe, die ihr hier investiert. 

Gruss
Stefan

### Wie könntest du dir vorstellen, wie deine Idee in CP aussehen könnte.

automatischer Start aller Helfer nach Spielstand laden.

### Gäbe es eine Alternative?

Alternativ: ein Befehl, der alle Helfer wieder aktiviert (Schaltfläche oder Tastenkombination)

### Screenshots

kein Screenshot verügbar

**Comment by Tensuko** [comment]
Mit absicht erst mal deaktiviert, ob wir das wieder einschalten, ist fraglich.
