### ISSUE TITLE
Working Width

### ISSUE THREAD

**Issue by AEcila** [Courseplay/Courseplay_FS25#236]
### Version

8.0.0.3

### SP/MP

SP (Singleplayer)

### What is your question about?

more later

### What is your question?

Is possibile to free the max Working width? I would like to set my vehicle Working width to 120
I looked at the code but I’m unable to find where you set the max at 54.9. You can work on that or is a problem with the comunication with the Giants code?

### Screenshots

No screenshot

**Comment by Tensuko** [comment]
Won't do that. We only do max what the basegame requieres.
Everything you do on your own is your own risk in breaking something.
