### ISSUE TITLE
Allow CP: Unload Combine when more than 1 trailers are attached

### ISSUE THREAD

**Issue by 19mariusz95** [Courseplay/Courseplay_FS25#238]
### Version

8.0.0.3

### SP/MP

SP (Singleplayer)

### What can be done with your idea?

I own a John Deere 8R 410 with two Brantner DD 24073/2 XXL trailers attached. However, I am unable to start the 'Unload Combine' job when the second trailer is connected to the first one. The job becomes available again once I detach the second trailer.

I am not aware of all limits that you have established for the project so I do not post this as a bug but if you consider this as one feel free to change the issue type

### If applicable, how would the user interface look like for this enhancement?

No need to implement any new UI

### Is there an alternative?

-

### Screenshots

-

**Comment by Tensuko** [comment]
Will not do that as we can't drive reverse with 2 trailers.
You can use a Truck with a volume + trailer, but not 2 trailer.
