### ISSUE TITLE
Custom Field

### ISSUE THREAD

**Issue by G9nrikh** [Courseplay/Courseplay_FS25#239]
### Version

8.0.0.3

### SP/MP

SP (Singleplayer)

### What is your question about?

Course creation

### What is your question?

How to create Custom Field by drow on the map (not HUD record)? I read monual, but i cannot found the button on the map.  I try evrything by clicking enywhere but nothing, May by this is coz of 3440*1440 resolution?

### Screenshots

![image](https://github.com/user-attachments/assets/205fedfe-d820-4138-8179-584a08adc7cb)

**Comment by Tensuko** [comment]
As written in the initial log, will be added later - patient!
