### ISSUE TITLE
Kurs Feldrand Generierung stimmt nicht ganz/ Drescher fährt weiter gerade aus

### ISSUE THREAD

**Issue by Bosche200** [Courseplay/Courseplay_FS25#241]
### Version

8.0.0.1

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Coursplay setzt roten punkt in einer Kurve.
der Drescher fährt gerade aus weiter außerhalb des Kurses.
hier kurzes Video des Problems Steam sei dank:
https://youtu.be/9QHPKAzgX0k

### Wie können wir diesen Fehler nachstellen?

mir unbekannt ob dies immer wieder auftritt.
Liegt es eventuell an der Einstellung Runde Ecken welche ich auf 0 gesetzt habe da ich bis jetzt schlechte Erfahrungen mit dieser Einstellung gemacht habe. Jedoch sollte er trotzdem nicht geradeaus weiter fahren oder ?

### Was hätte passieren sollen?

Drescher fährt weiter auf gerechneten Kurs.

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18278132/log.txt)

### Screenshots

![Screenshot 10](https://github.com/user-attachments/assets/e7b468bf-27c0-4ea8-a6fa-0fdb70975128)

**Comment by Tensuko** [comment]
Immer erst auf die neueste Version updaten.
