### ISSUE TITLE
Setting choice to keep implement lowered when going up/down the field.

### ISSUE THREAD

**Issue by Makion65** [Courseplay/Courseplay_FS25#242]
### Version

8.0.0.4

### SP/MP

SP (Singleplayer)

### What can be done with your idea?

In the tool settings menu, add an option to raise or keep lowered the tool when going around corners, and/or the up/down portions of the field. This is something I've though about for FS19 and FS22! There can often be a little corner missed here and there, and this would allow the option to potentially cover the field's headlands better when the tractor goes to turn around for the next pass.

### If applicable, how would the user interface look like for this enhancement?

In the fieldworks settings - settings center menu, it would add 1 more option to choose between 'rase tools to turn around' or 'keep tools lowered when switching direction'.

### Is there an alternative?

Yes, actually, you can edit a saved field to do this. It requires you to remove the end row and start row markers (The green and red waypoints, then I add a waypoint between those. I then drag that added marker out, then curve both sides to make it flow better. I did at one point make a tutorial video on how to do this, but, I don't think I ever uploaded it...

### Screenshots

![2300320_100](https://github.com/user-attachments/assets/152d37f2-0545-413b-88b0-45c2909ccfdd)

**Comment by Makion65** [comment]
Looking at the screenshot, I wanted to add that this comes in handier for large tools, like 15-20M wide +. Usually, most tractors can turn sharp enough with those wider tools, and the raising and lowering takes more time than just leaving the tool down and running the whole time.

**Comment by Tensuko** [comment]
Dont see the benefit.
Wont add this, sry.
If something get missed, it is mostly raise/lower or a wrong turning radius.

**Comment by Makion65** [comment]
One thing it could solve, is when a tractor tries backing something with
multiple pivot points, and it starts going in circles, or stops.

Idk if you'd have to add a different kind of way point - like the start/end
row ones, but a start/end turn, then it could initiate a sharp turnaround.

Anyhow, thanks for the reply. Wishing you the best.
