### ISSUE TITLE
Turning up and down rows

### ISSUE THREAD

**Issue by bozzdude** [Courseplay/Courseplay_FS25#244]
### Version

8.0.0.4

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

When turning up and down rows with the Krone Big M mower it lifts early and misses all the start and ends of each row. 

Also when turning up and down rows with a harvester it seems to turn like a battleship, missing the rows start and leaving huge swaths unharvested, the field looks like hot garbage.

### How can we reproduce this?

Just mow with a Big M or do some harvesting

### What did you expect to happen?

I expected it to start and finish each row fully.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18280041/log.txt)

### Screenshots

![image](https://github.com/user-attachments/assets/0c62d5c1-70e9-4650-a467-40b89d218d87)

**Comment by Tensuko** [comment]
BigM set lower tool to early.
Harvester I will check, but dont put 2 Issues in one.

BigM as said, will be fine.

**Comment by Tensuko** [comment]
Harvester works just fine.
![grafik](https://github.com/user-attachments/assets/b4f1aaf5-5b9e-4c69-aa03-f3ae44a14309)
