### ISSUE TITLE
worker stops doing rice field 

### ISSUE THREAD

**Issue by filippogrande** [Courseplay/Courseplay_FS25#247]
### Version

8.0.0.4

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

When the curseplay driver reaces the end of the field planting rice in a wet rice field the worker stops with the error: no field found while in the middle of the screen appears the game error that you cant plant out of the field, I've noticed that the game error also happens with the basegame worker but i just ignore it. If the worker uses headlands the problem doesn't occur as he doesn't leave the field

### How can we reproduce this?

have a wet rice field with a rice seeder don't use headlands, put the setting to 0 should be already like this, and start it at the end of the first row it should already have the problem 

### What did you expect to happen?

I tought it would continue to run 

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18281360/log.txt)

### Screenshots

![Screenshot 2024-12-31 130514](https://github.com/user-attachments/assets/77506f42-7d84-4120-8fa1-ce561f0275c7)
![Screenshot 2024-12-31 130534](https://github.com/user-attachments/assets/44a62736-015b-4d38-bed9-359677e1512e)

**Comment by Roby1164** [comment]
Filippo, non è un bug, ma un problema delle risaie come impostate dalla Giants.
Per il momento, ti consiglio di fare la semina del riso, con un'impostazione del margine campo, a 0.8/ 1 in modo da stringerlo leggermente e fare sempre almeno 3 giri perimetrali, solo in questo modo, la seminatrice non uscirà mai dal campo, mostrando quell'errore.

**Comment by Tensuko** [comment]
That is a problem of Giants.
Use at least headlands, and I would set it to 1 headland to round.

**Comment by filippogrande** [comment]
but the default worker works perfectly so it is a bug of the curseplay as it doesn't work with the default settings, I don't have any problem with the warning of beeing out of the field from the base game, I don't understand why it should stop the mod from working

**Comment by Tensuko** [comment]
Wont fix.
What to do I wrote already.
