### ISSUE TITLE
Horsch Maestro 9.75RX need Refill even when full

### ISSUE THREAD

**Issue by Jaspertphoek** [Courseplay/Courseplay_FS25#250]
### Version

8.0.0.4

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

When you start seeding, you get the message that the machine needs refilling, only it still contains 77% seed.

### How can we reproduce this?

Start seeding with Horsch Maestro 9.75RX with CP

### What did you expect to happen?

Start seeding with the Horsch Maestro 9.75RX using CP.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18281868/log.txt)

### Screenshots

![Afbeelding1](https://github.com/user-attachments/assets/fffff5fa-135f-40b8-af2f-201d4b103b37)

**Comment by Tensuko** [comment]
Front Tank attached yes or no?

**Comment by Jaspertphoek** [comment]
No fronttank

**Comment by Jaspertphoek** [comment]
It doesn't work with Front Tank either, FYI

**Comment by Tensuko** [comment]
![grafik](https://github.com/user-attachments/assets/fb593c1f-38cc-4b58-95f4-4dddd9e191d7)
Seems like you have the fertilizer option configured for that seeder.

Check that Setting in vehicle settings (fertilizer option) and turn it off.
![grafik](https://github.com/user-attachments/assets/d6c2e851-2474-46a5-96d1-8ef5acf2b17f)

**Comment by Tensuko** [comment]
Just tested myself, working all as intended.
Turn that option off if you have that configured and it works just fine.

**Comment by Jaspertphoek** [comment]
Funktioniert auch bei mir! Vielen Dank für die Hilfe!
