### ISSUE TITLE
please fix

### ISSUE THREAD

**Issue by ChrisBByoB** [Courseplay/Courseplay_FS25#58]
### Version

8.0.0.0

### Game Version

1.4.0.0

### SP/MP

MP (Multiplayer)

### What happened?

i have more then ten vehicles ive built a huge map and made a whole city etc love the mod but please allow up to 100 vehicles 

### How can we reproduce this?

have more then 10 vehicles game freezes at 98 percent 

### What did you expect to happen?

to load into my map

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18231329/log.txt)

### Screenshots

none

**Comment by Tensuko** [comment]
That is not a CP limit.

**Comment by Tensuko** [comment]
Too many mods with Errors in your logfile.
I don't see a CP related Error.

**Comment by ChrisBByoB** [comment]
That may be so but when i load into a different map works fine sooooo its definitely the 10 car thing crashes the gameSent from my Galaxy
-------- Original message --------From: Tensuko ***@***.***> Date: 12/23/24  11:51 AM  (GMT-05:00) To: Courseplay/Courseplay_FS25 ***@***.***> Cc: ChrisBByoB ***@***.***>, Author ***@***.***> Subject: Re: [Courseplay/Courseplay_FS25] please fix (Issue #58) 
Too many mods with Errors in your logfile.
I don't see a CP related Error.
