### ISSUE TITLE
game freeze on shop menu customisation 

### ISSUE THREAD

**Issue by gibson89** [Courseplay/Courseplay_FS25#62]
### Version

8.0.0.0

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

After cycling through options for tractor models after a few cycles (or clicking left to go to the last item) the cursor will disappear and the camera will bind to mouse movement (as if holding left click) right clicking will return the cursor and you can continue to click or buy but to leave the shop requires clicking on the esc option in lower right the keyboard won't function. Exiting the menus completely back into the game is possible but none of the controls work and a reset of the game is the only solution I've found.

### How can we reproduce this?

I can make it happen on a brand new game, CP the only active mod and just go straight to shop select something that's configurable then change configs a few times - how quickly you cycle seems to have an effect too (specifically the fendt 900 in my no other mods test after 6 clicks on engine setup but issue isn't specific to that item)  

### What did you expect to happen?

The game shouldn't lock up

### Attach your log.txt!

[log (1).txt](https://github.com/user-attachments/files/18231806/log.1.txt)

### Screenshots

https://github.com/user-attachments/assets/a7a59d06-090c-4a34-aacd-c7dcee40c9dd

**Comment by gibson89** [comment]
I will recreate again without the mods in mod folder to clean log text

**Comment by Tensuko** [comment]
Please use drag and drop for the log.txt! Do not copy your log as text in here.

**Comment by Luscion** [comment]
I run into the same issue when modifying vehicles in the shop, i've attached my log file

**Comment by Luscion** [comment]
Running into the same issue as well, attached my log file [log.txt](https://github.com/user-attachments/files/18231844/log.txt)

**Comment by gibson89** [comment]
> Please use drag and drop for the log.txt! Do not copy your log as text in here.

Apologies - been about a decade since I done this type of thing

**Comment by aurelien2023** [comment]
seems your computer have low specs... 
Did you hit the giants minimal config for FS25 ?
works fine for me with Vario900 
[log.txt](https://github.com/user-attachments/files/18231909/log.txt)

**Comment by gibson89** [comment]
> seems your computer have low specs... 
> Did you hit the giants minimal config for FS25 ?
> works fine for me with Vario900 
> [log.txt](https://github.com/user-attachments/files/18231909/log.txt)
> 

It's the newer steamdeck which is comparable with their min specs. I did try to recreate on the vanilla game and it wouldn't happen until courseplay was loaded

**Comment by willw215** [comment]
Similar issue as above. (Attached log file)Running on a dedicated server. Course play works perfectly until i want to customise something in the shop. When i manage to get out of the shop the game crashes (but not to the desktop) all buildings disapear and all vehicles are stationary etc. From the console its lots of LUA errors as shown in the log file. Thank you for this mod. If there is a specific way you would like to replicate this please let me know. Cheers
[log.txt](https://github.com/user-attachments/files/18233101/log.txt)

**Comment by Vlandarr** [comment]
Same experience, both SP and MP (dedicated server).  Managed to reproduce it within minutes on a new vanilla SP save
[log.txt](https://github.com/user-attachments/files/18233444/log.txt)

**Comment by gibson89** [comment]
I have been playing for the past few hours and waiting a second after every config change without issue (I wait for the loading icon to disappear then give an extra beat to be safe) so it would seem that may have something to do with it.

**Comment by u4gTheReal1** [comment]
Sorry I just logged the same issue, I should have read before I logged the issue. My apologies.

**Comment by bf312344** [comment]
Same issue but I found a temporary workaround, when customizing vehicle slowly e.g. switching tire manufacturer once and waiting a second or two until the model fully loads it works fine. Clicking through options fast instantly bugs the game and gives a flood of
 ```
Error: Running LUA method 'update'.
mods/FS25_Courseplay/scripts/specializations/CpCourseManager.lua:227: attempt to index nil with 'courses'
```

**Comment by gibson89** [comment]
> Same issue but I found a temporary workaround, when customizing vehicle slowly e.g. switching tire manufacturer once and waiting a second or two until the model fully loads it works fine. Clicking through options fast instantly bugs the game and gives a flood of
>  ```
> Error: Running LUA method 'update'.
> mods/FS25_Courseplay/scripts/specializations/CpCourseManager.lua:227: attempt to index nil with 'courses'
> ```

Bug squashed for me in version 8.0.0.1 have you updated your CP?

**Comment by JusAJ** [comment]
I had this same bug happening again, in version 8.0.03. Attached you will find the log.txt
[log.txt](https://github.com/user-attachments/files/18270783/log.txt)
It seems that indeed as the previous commenter qoutes, it happenes while scrolling quite fast through different customization options.
If I can do anything to point something down I'd be glad to help

**Comment by Tensuko** [comment]
Different Error.

**Comment by b-fordy** [comment]
Seeing this issue once again. Running Courseplay v8.0.1.3 on patch 1.7

[log.txt](https://github.com/user-attachments/files/19721862/log.txt)

**Comment by Tensuko** [comment]
One look in your own mod:
2025-04-12 15:30 Error: Running LUA method 'update'.
C:/Users/blake/OneDrive/Documents/My Games/FarmingSimulator2025/mods/FS25_exhaustExtension/src/ExhaustExtension.lua:45: attempt to index nil with 'particleSystems'

Not a CP Issue.

**Comment by b-fordy** [comment]
Realized this right after I commented, sorry for that haha
