### ISSUE TITLE
Game freezes after leaving the Server.

### ISSUE THREAD

**Issue by regs1980** [Courseplay/Courseplay_FS25#65]
### Version

8.0.0.0

### Game Version

1.4.0.0

### SP/MP

MP (Multiplayer)

### What happened?

After the client has left the server, the game freezes on the client if the CP helper is active on the server.

### How can we reproduce this?

Join the server. 
Buy a field or use your own field. 
Buy a tractor and implement, no matter which one.
Create a CP course and activate the helper.
After starting the CP helper, disconnect the client from the server. 

### What did you expect to happen?

After starting the CP-Helper and disconnecting from the server, the game should not freeze.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18232011/log.txt)

### Screenshots

![2024-12-23 18_09_55-Greenshot](https://github.com/user-attachments/assets/91922e98-fc36-4a0c-a60a-d0f513bc6a57)

**Comment by regs1980** [comment]
Works very well. Thanks

**Comment by schwiti6190** [comment]
@regs1980 Are you refering to this push https://github.com/Courseplay/Courseplay_FS25/commit/3a30e9e835f94ff7691e6c43aaff3faeb4da3947. If so could you still post a log as there should be a callback, even if it is not lethal. I would like to identify the real reason for the bug and not the result? :)

**Comment by regs1980** [comment]
As requested the log.

[log.txt](https://github.com/user-attachments/files/18234409/log.txt)

**Comment by schwiti6190** [comment]
@regs1980 Could you try it again with this version https://github.com/Courseplay/Courseplay_FS25/pull/77 and post a log file? Thanks in advanced this is really helpful:)

**Comment by regs1980** [comment]
@schwiti6190 
I tested it and here is the log of it.
No more LUA call stack in the log.
[log.txt](https://github.com/user-attachments/files/18236408/log.txt)

**Comment by schwiti6190** [comment]
@regs1980 Thank you very much for testing this, seems to be fixed :)
