### ISSUE TITLE
No Button to create folder in Coursemanager

### ISSUE THREAD

**Issue by Jaguar95** [Courseplay/Courseplay_FS25#66]
### Version

8.0.0.0

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

I try to create an course - that works - on Zielonka Field 89. But when i try to save it in the Coursemanager, there is noch Button to create folders. And without an folder, i can't save.

### Wie können wir diesen Fehler nachstellen?

Create an course an try to save it.

### Was hätte passieren sollen?

Button to create folders in Coursemanager.

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18232150/log.txt)

### Screenshots

![screenshot_2024_12_23_19-14-06-Nr_01](https://github.com/user-attachments/assets/6ff3e0e3-129b-4542-85f4-e3cc6f9417f6)

**Comment by Tensuko** [comment]
Fixed in next Release, it is only there without a loaded course right now, not rly a bug but yeah can be annoying.
Just wait for 8.0.0.1 untill then enter any vehicle without that course and create a folder first.

**Comment by Jaguar95** [comment]
Thanks for your response
