### ISSUE TITLE
Game crashes completly

### ISSUE THREAD

**Issue by Schoofje** [Courseplay/Courseplay_FS25#67]
### Version

8.0.0.0

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

Game crashed completely, no input possible from mouse nor keyboard.  

### How can we reproduce this?

happened twice now without warning

### What did you expect to happen?

i couldn`t pinpoint a specific function that caused the crash

### Attach your log.txt!

[Schoofje](https://gist.github.com/Schoofje) / [gist:05c8b369bf2685c5595a38d1046d962b](https://gist.github.com/Schoofje/05c8b369bf2685c5595a38d1046d962b)

### Screenshots

![2300320_321](https://github.com/user-attachments/assets/c7967650-5899-4b54-ac0b-a16be24bf2b8)

**Comment by Tensuko** [comment]
Same Error as in #62
Duplicate.
