### ISSUE TITLE
wrong course with Big M 

### ISSUE THREAD

**Issue by Unaragan** [Courseplay/Courseplay_FS25#69]
### Version

8.0.0.0

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

during course generation this happend with a BigM on a connected and extended field 

### How can we reproduce this?

trieed diffrent time to generate a course with an Big M

### What did you expect to happen?

funy course

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18232885/log.txt)

### Screenshots

![Screenshot 2024-12-22 211937](https://github.com/user-attachments/assets/f2db9e70-f07a-4637-a3e5-d1296f2c1ceb)

**Comment by Tensuko** [comment]
The generator is not related to any tool.
So its not baiscally the BigM, the question is what settings you used.

**Comment by Tensuko** [comment]
Same callstack like in #71 ?

**Comment by MEminK66** [comment]
I also encountered this problem. When I activate the rows follow field edge curve option, it creates the course similar to this.

**Comment by Tensuko** [comment]
Thats why that is an expert option and actually we wrote in the help that when the course is not proper, it won't work.
So we won't fix that.
If that is the same problem here, won't fix.

**Comment by pvaiko** [comment]
Callstack already fixed in https://github.com/Courseplay/Courseplay_FS25/pull/57
