### ISSUE TITLE
Ballen wickler

### ISSUE THREAD

**Issue by Drakus991** [Courseplay/Courseplay_FS25#71]
### Version

8.0.0.0

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Sobald der Ballenwickler gestartet wird ( cp) öffnet und er schließt er sich nur und beendet dann die Arbeit gerät Kuhn 4014 ballenwickler 

### Wie können wir diesen Fehler nachstellen?

habe einen auftrag mit geliehnen  Fahrzeugen angenommen sobald Traktor mit wickler auf dem Feld stehen und man CP Startet öffnet und schließt er nur und beendet die arbeit

### Was hätte passieren sollen?

beim start hätte er aufklappen müssen und direkt anfangen müssen zu wickeln

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18233059/log.txt)
[log.txt](https://github.com/user-attachments/files/18233060/log.txt)

### Screenshots

![Unbenannt](https://github.com/user-attachments/assets/7f63d1ee-9d47-462d-8673-2e6e13462677)

**Comment by pvaiko** [comment]
Callstack fixed by https://github.com/Courseplay/Courseplay_FS25/pull/57

**Comment by Drakus991** [comment]
das problem besteht weiterhin auch mit der neuen version ballenwickler klappt auf und wieder zu ohne den job zu starten

**Comment by pvaiko** [comment]
Hast bestimmt ein Log mit debug, oder?

**Comment by Drakus991** [comment]
was ist das entschuldige soweit bin ich nicht in der materie

**Comment by soap-2583** [comment]
Hab in den Mod Einstellungen "Fahrzeug-Debug" aktiviert. Hoffe das reicht.

https://gist.github.com/soap-2583/2bc133fc97b0cb8b2bf53cfba995e300

**Comment by pvaiko** [comment]
Es ist kein callstack mehr, wir finden die Ballen nicht, habt ihr den korrekten Ballentyp ausgewáhlt? @Tensuko  hat bestimmt tips.

**Comment by Drakus991** [comment]
Ballentyp ist ungewickekt oder alle sammeln und wickel und es ist egal ob Quader oder rund ballen der wickler öffnet und schließt dann fährt das Fahrzeug eine runde und sagt Arbeit beendet

**Comment by marcLBo** [comment]
Bei mir verhält sich der Ballenwickler genauso.

Version: 8.0.0.1

Relevanter Callstack:

```
2024-12-25 02:25 :29 [info lp50344] Scanning field 15 on Hutan Pantai, prefer custom fields false
2024-12-25 02:25 44.000000
2024-12-25 02:25 -53.334330
2024-12-25 02:25 
Script error: Divide by zero error.
LUA call stack:
  =C:/Users/xx/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/Course.lua:970 createFromNode
  =C:/Users/xx/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/ai/turns/TurnManeuver.lua:287 adjustCourseToFitField
  =C:/Users/xx/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/ai/turns/TurnManeuver.lua:400 init
  =C:/Users/xx/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/ai/turns/TurnManeuver.lua:436 init
  =C:/Users/xx/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/CpObject.lua:44 
  =C:/Users/xx/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/ai/turns/AITurn.lua:756 generateCalculatedTurn
  =C:/Users/xx/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/ai/turns/AITurn.lua:592 startTurn
  =C:/Users/xx/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/ai/turns/AITurn.lua:299 finishRow
  =C:/Users/xx/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/ai/turns/AITurn.lua:240 getDriveData
  =C:/Users/xx/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/ai/strategies/AIDriveStrategyFieldWorkCourse.lua:187 getDriveData
  =dataS/scripts/vehicles/specializations/AIFieldWorker.lua:330 updateAIFieldWorker
  =dataS/scripts/vehicles/specializations/AIFieldWorker.lua:310 onUpdate
  =[C]:-1 xpcall
  =C:/Users/xx/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/CpUtil.lua:262 try
  =C:/Users/xx/Documents/My Games/FarmingSimulator2025/mods/FS25_Courseplay/scripts/specializations/CpAIFieldWorker.lua:307 onUpdate
  =dataS/scripts/utils/Utils.lua:601 
  =dataS/scripts/specialization/SpecializationUtil.lua:56 raiseEvent
  =dataS/scripts/vehicles/Vehicle.lua:1890 update
  =dataS/scripts/network/NetworkNode.lua:164 updateActiveObjects
  =dataS/scripts/network/Server.lua:64 update
  =dataS/scripts/BaseMission.lua:1017 update
  =dataS/scripts/FSBaseMission.lua:1936 update
  =dataS/scripts/mission00.lua:658 update
  =dataS/scripts/main.lua:1195 update
```

**Comment by Tensuko** [comment]
Ich schau gleich mal.

**Comment by Tensuko** [comment]
Also ein Callstack gibt es nicht mehr (für neue Geräte, vlt ein Reset machen).
Aber er klappt das Gerät direkt wieder ein und fährt zum Ziel Marker und beendet die Arbeit.
Ob das an der Wickelfolie liegt weil "voll" ?
Hab es mit Mission und eigenem Feld getestet.

[log.txt](https://github.com/user-attachments/files/18245955/log.txt)

**Comment by Drakus991** [comment]
Ich leihe mir bei einer Mission bzw Vertrag das Gerät auch eins Traktor und ein ballenwickler Kuhn 4014 fahre ans Geld habe es sogar versucht ihn manuell hinzu fahren und dann ballen sammeln und wickeln ausgewählt aber es funktioniert nicht er klappt auf und sofort wieder zu fährt sinnlos kurz Rum und beendet die Arbeit

**Comment by Drakus991** [comment]
Wie meinst du das mit dem reset habe auch ein neues savegame probiert alle mods aus bis auf courseplay und genau das selbe problem

**Comment by lisekv1** [comment]
Hello, I have the same problem, for full understanding I am sending you a video of what it looks like and the logs
https://youtu.be/D9lIxHnISnA
[log.txt](https://github.com/user-attachments/files/18247480/log.txt)

**Comment by lisekv1** [comment]
This is not a problem only with this wrapper, here I am sending a video in which there is a different wrapper and the problem still occurs 
https://youtu.be/ZneMkGDKERQ

**Comment by lisekv1** [comment]
Creating a custom field here does not fix the problem https://youtu.be/hexoAf4KsHA

**Comment by Tensuko** [comment]
Guys, chill, let us do our work we will find a solution.
We dont need 100 exampls:)

**Comment by lisekv1** [comment]
> Guys, chill, let us do our work we will find a solution. We dont need 100 exampls :)

I'm not rushing you, I want everything to be well understood and visible.

**Comment by pvaiko** [comment]
With the current version on main (6eb23ababe7a366714e5048cb4f7bde7eb8f86f4) the Kuhn SW4014 works if the offset is set to 1.8, with **round** bales.

It does **not work** with square bales. It does not work manually either, it shows "This bale is not supported". 

So please, before reporting that CP does not work, try to wrap the bales manually. If it does not work, CP won't work either. If it works, post a log with debug activated.

**Comment by Drakus991** [comment]
Guten Morgen also manuell kann ich sowohl quader als auch Rundballen super Wickeln kann es probieren mit der 1.8 m Einstellung Ob es dann funktioniert

**Comment by Drakus991** [comment]
![Unbenannt](https://github.com/user-attachments/assets/033de258-072b-4d01-8330-bf68c3a7eaba)

**Comment by Drakus991** [comment]
[log.txt](https://github.com/user-attachments/files/18252331/log.txt)

**Comment by Drakus991** [comment]
habe den debugger angemacht und nun die log datei angehängt hoffe das ist so richtig

**Comment by lisekv1** [comment]
> With the current version on main ([6eb23ab](https://github.com/Courseplay/Courseplay_FS25/commit/6eb23ababe7a366714e5048cb4f7bde7eb8f86f4)) the Kuhn SW4014 works if the offset is set to 1.8, with **round** bales.
> 
> It does **not work** with square bales. It does not work manually either, it shows "This bale is not supported".
> 
> So please, before reporting that CP does not work, try to wrap the bales manually. If it does not work, CP won't work either. If it works, post a log with debug activated.

I won't test it now, but surely this one wrapper shouldn't be the only thing that works in fashion?

**Comment by lisekv1** [comment]
Unfortunately, when I take on a task of wrapping round bales, I use the Kuhn Sw 4014 and set it to 1.8..Nothing changes, still the same problem.

**Comment by lisekv1** [comment]
I am sending a video of everything set up and logs https://youtu.be/M8sW9pgTinE
[log.txt](https://github.com/user-attachments/files/18252844/log.txt)

**Comment by pvaiko** [comment]
Get me a savegame.

**Comment by lisekv1** [comment]
> Get me a savegame.

Unfortunately I'm not at home today. But generally this happens with every new savegame

**Comment by Tensuko** [comment]
I will do it later.

**Comment by pvaiko** [comment]
> Unfortunately I'm not at home today. But generally this happens with every new savegame

Except on mine. I wouldn't ask for one if I was able to reproduce it.

**Comment by regs1980** [comment]
It works with bales that you have created yourself.
Only the mission bales created by the game are not recognized. 

I dropped two additional bales with the PowerTools and the wrapper only recognized the two bales on the field, it did not recognize the mission bales.

**Comment by lisekv1** [comment]
> It works with bales that you have created yourself. Only the mission bales created by the game are not recognized.
> 
> I dropped two additional bales with the PowerTools and the wrapper only recognized the two bales on the field, it did not recognize the mission bales.

Well, it's a shame that only created bales should also work with contracts. There is no information anywhere that it won't work

**Comment by regs1980** [comment]
@lisekv1 
The CP team will find a solution.

**Comment by lisekv1** [comment]
> Get me a savegame.

[savegame14.zip](https://github.com/user-attachments/files/18255783/savegame14.zip)

**Comment by lisekv1** [comment]
Of course, we are still talking about the bales from the contract

**Comment by Tensuko** [comment]
Let us do our work.... And have patient and wait.
Locked for now.
