### ISSUE TITLE
Courseplay without Courses???

### ISSUE THREAD

**Issue by Jimkerk** [Courseplay/Courseplay_FS25#74]
### Version

8.0.0.0

### SP/MP

SP (Singleplayer)

### What is your question about?

Course creation

### What is your question?

First of all Thank you for your work.
So now too my points. I am very Sad that CP again depents on AD. AD sucks, sorry , but thats my opinion .
I really wish that we could drive in our own Courses with CP like in the past. 
It was esay and you can make courses on demand .  

And aktivate pls the tiretracks for the silohelper. that looks lame without it. 
The Silohelper also folds up the siloroller.....

please let us make our own Courses again With Courseplay
We have Courseplay allready ingame for the fields.....wasted energy

### Screenshots

![Farming Simulator 2025 Screenshot 2024 12 23 - 23 59 39 19](https://github.com/user-attachments/assets/9b119786-b6c5-4eca-a08b-db60c93cbde9)

**Comment by schwiti6190** [comment]
@Jimkerk I can partly understand your reason, but this wont result in anything for now. 
We are open to possiblities in a distance future for alternatives, but they wont be released in the near future :)
We decided to drop street work, so we can perfekt/improve all other aspects of the game, especially the gui experience for newer Players and it was worth it, if I might say so bluntly :) Let's see what the furture might hold, but if it happens, than it will take a lot of time, so don't get your hopes up:)
