### ISSUE TITLE
Tastenbelegung GUI und Mouse-Zeiger arbeiten inkorrekt

### ISSUE THREAD

**Issue by Horschde** [Courseplay/Courseplay_FS25#75]
### Version

8.0.0.0

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Ich habe das aktivieren / deaktivieren des Mousezeigers auf die mittlere Mousetaste gelegt.
Ich habe das aktivieren / deaktivieren des GUI die Mousetaste 5 gelegt.

Startzustand ist nun, weder GUI noch Mousezeiger sind aktiviert.

Wenn ich den Mousezeiger, mit der mittleren Mousetaste aktiviere, wird auch das GUI gleich mit aktiviert.
Nun kann ich den Mousezeiger, mit der mittleren Mousetaste, wahlweise ein- oder ausschalten.
Das GUI kann ich mit dem drücken der Mousetaste 5 nicht deaktivieren, statt das GUI zu schließen, wird mit der Mousetaste 5 nur der Mousezeiger deaktiviert / aktiviert. Das GUI kann ich nur per Mouseklick auf das X vom GUI wieder schließen.

Neuer Test mit Startzustand, weder GUI noch Mousezeiger sind aktiviert.

Wenn ich das GUI, mit der Mousetaste 5 aktiviere, wird der Mousezeiger gleich mit aktiviert.
Jetzt passiert das gleiche, wie oben schon beschrieben.

### Wie können wir diesen Fehler nachstellen?

So wie es oben geschrieben steht.

### Was hätte passieren sollen?

Es sollte sowohl der Mousezeiger, als auch das GUI per separater Tasten einzeln ein- als auch auch auszuschalten gehen. So wie diese Funktionen auch im LS22 CP funktioniert haben.

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18234079/log.txt)

### Screenshots

<img width="1280" alt="Farming Simulator 25 Screenshot 2024 12 23 - 23 31 37 84" src="https://github.com/user-attachments/assets/8775ae0a-f7e5-457e-ac0f-d911f34b74a9" />

**Comment by Tensuko** [comment]
Um es mal einfacher zu formulieren.....
Mauszeiger an/aus macht das HUD auf, schließt es aber nicht, sonder natürlich nur durch X drücken.
Die Tastenbelegung macht das HUD auf, schließt es aber auch nicht, sondern macht nur den Mauszeiger aus.
Richtig?

**Comment by Friendlyx** [comment]
JA gneau das
