### ISSUE TITLE
Missing / No Add or create folder in the course manager

### ISSUE THREAD

**Issue by C0d3Junk13x** [Courseplay/Courseplay_FS25#76]
### Version

8.0.0.0

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

Just downloaded the newest version (8.0) and there is no "add or create folder button" in the course manager.

### How can we reproduce this?

No "add or create folder button" in the course manager.

### What did you expect to happen?

No "add or create folder button" in the course manager.  See attached image.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18234280/log.txt)

### Screenshots

![No create folder button](https://github.com/user-attachments/assets/e429add5-62b5-481c-a38b-ce6ebd4ae8b2)

**Comment by schwiti6190** [comment]
@C0d3Junk13x Hi will be fixed in the next version :)

**Comment by C0d3Junk13x** [comment]
No problem, just pointing it out so you can spit polish the small errors. Still the best mod for FS ever made. I almost quit playing FS25 because the AI sucks.  Keep up the great work.

**Comment by Tensuko** [comment]
#66
