### ISSUE TITLE
Tools sometimes stop working after transition from headland to center or vice versa

### ISSUE THREAD

**Issue by krookoo** [Courseplay/Courseplay_FS25#79]
### Version

8.0.0.0

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

Combine lifts the header and bypasses 1 row.
After passing this row the next one mows normally.
I used for this work two combines.
Both have same issue.
Its first "long run" after circle.

### How can we reproduce this?

Dont know. Its second course what i generated (i also cant save course).
First course on other merged field working properly (same combines, crop rape).
Both courses for 2 combines stack.

### What did you expect to happen?

Dont know.
Screenshots and log has little mismatch, because i generate log after works to reproduce console logs.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18235481/log.txt)

### Screenshots

![fsScreen_2024_12_23_04_19_59](https://github.com/user-attachments/assets/1414f614-a250-4685-8174-e08192a21766)
![fsScreen_2024_12_23_04_20_05](https://github.com/user-attachments/assets/cf2e1412-41a7-4379-ad3f-33da03d839ea)
![fsScreen_2024_12_23_04_36_43](https://github.com/user-attachments/assets/8581b85a-c0b4-4417-94ec-42993bc65506)

**Comment by Tensuko** [comment]
Strange.... I wasn't able to reproduce anything of this.
Single course, multicourse, all not a single problem....
You may try 8.0.0.2 if that still happens there?

**Comment by OpiGunnar** [comment]
verwende 8.0.0.2

**Comment by krookoo** [comment]
The issue has been fixed in version 8.0.0.2.
I can send my savegame if you want check it in your PC.
I stop CP when combine bypasses row and when i again start CP, combine working properly.
