### ISSUE TITLE
Combine mode fails with "No Path" after one run

### ISSUE THREAD

**Issue by ElijahSimonson** [Courseplay/Courseplay_FS25#80]
### Version

8.0.0.0

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

When running a tractor/trailer in combine empty mode the tractor will stop after one run and then exit courseplay showing No Path error. Occurs with both combine and vegetable harvesters.

### How can we reproduce this?

Start combine (or any other harvester)
Set field and location next to field for tractor.
Run harvester
Tractor will start pathing then either:
A) Drive off randomly
B) Sit still and error No Path
C) Follow the harvester for 1 line then pull back and immediately error as the harvest starts the second line

### What did you expect to happen?

Tractor to follow the harvester (vegetable) down each line, repositioning after each end.
Tractor to empty combine then hold until next empty request.

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18236597/log.txt)

### Screenshots

![Screenshot 2024-12-24 191601](https://github.com/user-attachments/assets/75087d76-7e47-41a9-aba9-3a32d9aedcef)
![Screenshot 2024-12-24 191637](https://github.com/user-attachments/assets/b65463a6-2539-40b4-aef5-b8cf6dd33068)

**Comment by pvaiko** [comment]
I need a savegame for this.

**Comment by ElijahSimonson** [comment]
[savegame2.zip](https://github.com/user-attachments/files/18237198/savegame2.zip)

This is the save the issue is occuring in.

**Comment by pvaiko** [comment]
Forgot to say I need a savegame preferably with no mods. If there are mods, I need a link to them. Link should be a proper webpage, no ads, scams, etc.

**Comment by ElijahSimonson** [comment]
[savegame2.zip](https://github.com/user-attachments/files/18237442/savegame2.zip)

That should do it. No mods other than Courseplay active in this one. Had to swap out tractors as they were modded, however retested and issue still exists.

**Comment by proactivepcc** [comment]
If it helps, I was having the same issue with vegetable harvester (spinach) and noticed the pipe on the harvester wasn't extending.  Don't know if that's intended or if it may be contributing to error?
