### ISSUE TITLE
Loading screen is stuck on 98%

### ISSUE THREAD

**Issue by ravotto** [Courseplay/Courseplay_FS25#82]
### Version

8.0.0.0

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

Loading screen is stuck on 98% on an 200+ save riverbend springs. seems to work on a new game. Tried with and witout other mods on that save. It loads without course play.

### How can we reproduce this?

enable courseplay on my save on riverbend springs

### What did you expect to happen?

the game to start with courseplay enabled

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18237177/log.txt)

### Screenshots

![image](https://github.com/user-attachments/assets/56ba432f-e2a4-4a71-b459-e671e97b95b3)

**Comment by Tensuko** [comment]
2024-12-24 08:35 Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
dataS/scripts/vehicles/specializations/AIDrivable.lua:728: invalid argument #1 to 'max' (number expected, got nil)

Mod conflict with something.
We can't support all mods, especially in this state.
Remove mod by mod to find out wich one.
