### ISSUE TITLE
Buying Items

### ISSUE THREAD

**Issue by u4gTheReal1** [Courseplay/Courseplay_FS25#83]
### Version

8.0.0.0

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

After buying items my character seems to freeze. The game is still active as the time is still moving and the people and cars are moving. 

### How can we reproduce this?

Buy anything on the market 

### What did you expect to happen?

I expected the game to continue

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18237372/log.txt)

### Screenshots

A screenshot would not be helpful in this scenario

**Comment by u4gTheReal1** [comment]
I see that if you do not customize anything the game works fine. No freezing of my character.

**Comment by Tensuko** [comment]
Duplicate #62
