### ISSUE TITLE
EPD540e wird nicht als Ernter erkannt.

### ISSUE THREAD

**Issue by Wolfurus** [Courseplay/Courseplay_FS25#84]
### Version

8.0.0.0

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Über eine Mission hab ich den EPD540e gemietet. Dieser wurde aber leider nicht als Ernter erkannt.

Mit den MKB-4TR und BP2140e werde ich es ehestmöglich noch nachtesten.

### Wie können wir diesen Fehler nachstellen?

Wie oben beschrieben.
EPD540e besorgen und mit CP versuchen zu starten!

### Was hätte passieren sollen?

CP soll EPD540e als Ernter erkennen.

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18237724/log.txt)

### Screenshots

![image](https://github.com/user-attachments/assets/43fe82ff-0c5e-4c63-9317-0277ce5e9338)

**Comment by Tensuko** [comment]
Gekauft, gemietet, und mit Mission geholt, alles kein Problem.
Könnte ein Modconflict sein.

Da ist ein Callstack von  FS25_roundBalerExtension auch wenn es unwahrscheinlich ist, dass es das Problem ist.

Das geht auch nicht mit klick auf Siloarbeit?
Würde mal versuchen ob es an einer anderen Mod liegt...

**Comment by Wolfurus** [comment]
Ja, den Callstack gibt es schon länger. (sollte ich auch mal schauen, warum. Bin aber zu faul grad. 😄 )

Hab jetzt noch ein paar mal rumprobiert.
Fahrzeug bleibt bei dem Overlay immer nur auf Siloarbeit.
Aber wenn ich über den Zielpunkt-Button ins Kursmenü geh, kann ich einen Kurs erstellen und auch starten.
![image](https://github.com/user-attachments/assets/072d2635-0bbc-48fe-b079-aa8b35f824d8)
Sieht dann so aus.

Kann es auch daran liegen, dass die Mission und auch das Fahrzeug schon auf der Map gab, als ich CP dazu geladen habe?

**Comment by Tensuko** [comment]
Kann durchaus sein, habe die Situation noch nicht gehabt mit "schon vorhanden".
Müsste ich mal probieren, aber heute nicht mehr :)

**Comment by Wolfurus** [comment]
Versteh ich voll und ganz. 👍 
Wünsch dir und auch dem restlichen CP-Team frohe Weihnachten und ein guten Rutsch ins neue Jahr.

Ihr macht eine echt geile Arbeit und ohne euch ist LS kein LS 😄

**Comment by Wolfurus** [comment]
So, hab ein paar mal rumprobiert.

Lag wohl wirklich daran, dass zuerst der Ernter auf dem Feld/Map war und danach CP hinzugefügt wurde.

Wenn ihr das nicht als Bug anseht, kann das Issue geschlossen werden.

Schöne Grüße
euer Wolf
