### ISSUE TITLE
F1 menu missing

### ISSUE THREAD

**Issue by KissFarkass** [Courseplay/Courseplay_FS25#91]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

F1 menu is missig in vehicles with the 8.0.0.1 update. I used only the courseplay, no other mods.

### How can we reproduce this?

F1

### What did you expect to happen?

To apear the help menu

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18240739/log.txt)

### Screenshots

![F1](https://github.com/user-attachments/assets/6cf11a3a-0e59-4db5-9ae2-2c9e4d1293fa)

**Comment by Roby1164** [comment]
I confirm, and when switching from one vehicle to another, the log reports this error:
![Screenshot_16](https://github.com/user-attachments/assets/35ae27af-15dc-4d94-b7e0-6325ade71881)

**Comment by KissFarkass** [comment]
Update: If i delete courseplay.xml from mod settings the F1 menu  come back.

**Comment by Roby1164** [comment]
> Update: If i delete courseplay.xml from mod settings the F1 menu come back. Update 2: If Action event help is enabled the F1 menu disappears.

I confirm

**Comment by romyao** [comment]
yes, I have same issue, after checking log, it's same as above :)

**Comment by Tensuko** [comment]
I don't have that problem so I can't rly test if it is fixed, can you test the state from PR https://github.com/Courseplay/Courseplay_FS25/pull/103 and check if the error is gone?

**Comment by Roby1164** [comment]
> I don't have that problem so I can't rly test if it is fixed, can you test the state from PR #103 and check if the error is gone?

No, I tried that change, but it doesn't work.
But if I revert to 8.0.0.0, the problem doesn't exist, so it's something in 8.0.0.1 that creates it.

**Comment by KissFarkass** [comment]
> I don't have that problem so I can't rly test if it is fixed, can you test the state from PR #103 and check if the error is gone?

 If Action event help is enabled still no F1 help menu

**Comment by schwiti6190** [comment]
@Roby1164 @KissFarkass Can you try it again with the latest push to the PR ?

**Comment by KissFarkass** [comment]
Now the help menu works with the action event help enabled.

**Comment by romyao** [comment]
awesome, works for me as well. F1 menu shows as usual during a quick test, no error in log either.
thanks team!!
