### ISSUE TITLE
No saw function with Dalbo Powerchain

### ISSUE THREAD

**Issue by svensigi** [Courseplay/Courseplay_FS25#92]
### Version

8.0.0.1

### Spielversion

1.4.0.0

### SP/MP

SP (Singleplayer)

### Was ist passiert?

Tried to Saw with the Dalbo Powerchain (Grass) doesnt work, its only cultivating.

### Wie können wir diesen Fehler nachstellen?

Using Dalbo Powerchain, try to directly saw into a stubble field. 

### Was hätte passieren sollen?

Sawing and cultivating. Works with "KI" Helper

### Bitte hänge deine log.txt an!

[log.txt](https://github.com/user-attachments/files/18240995/log.txt)

### Screenshots

To big of a File,

**Comment by svensigi** [comment]
After testing a bit more, is also the KI Helper doing the same, sometimes it saws, sometimes not, so maybe ingame bug.

**Comment by Tensuko** [comment]
Does it also not work, if you turn on the seed option?
![grafik](https://github.com/user-attachments/assets/41f76674-a290-4a3b-9a6c-53c78781bfdc)

**Comment by Tensuko** [comment]
![grafik](https://github.com/user-attachments/assets/6f78e6fb-5e12-44c7-adda-413f0c4ff170)
![grafik](https://github.com/user-attachments/assets/ee1ac23d-8b55-47a6-9780-3601c6fc75e5)
Looks pretty good to me.

**Comment by svensigi** [comment]
Thats not the same machine i used. Also i used it on non prepared ground (after harvest)
![Screenshot_2024-12-25-20-05-33-65_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/668d3dc4-13df-42c4-9017-589cb07369a7)

**Comment by Tensuko** [comment]
No support for mods from none modhub mods, sry.
We have to make that cut at some point.
If that one also not saw with Giants Helper, the modder did not stick to the AI guidlines from Giants.

Won't fix.

**Comment by BalticHawk** [comment]
It’s not a mod. The screenshot is from giants fact sheet.

**Comment by Tensuko** [comment]
Sry I was confused by this... 
![grafik](https://github.com/user-attachments/assets/2c0b5ab6-cdb9-4caf-9d5a-aeb3702e328e)

**Comment by Tensuko** [comment]
Exactly the same. It just works when turn on the seed option (ofc you need the seeder configured in the shop).
![grafik](https://github.com/user-attachments/assets/d3c9b896-6a47-4e65-9ef5-a92a63101ee6)
![grafik](https://github.com/user-attachments/assets/188a0e03-73f0-4935-92be-b0d61f8efeea)
