### ISSUE TITLE
Return to Starting point

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS25#93]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

CP Helper not returning to starting point when option is selected

### How can we reproduce this?

Selected option to return to starting point, run course

### What did you expect to happen?

Helper to return to starting point

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18241341/log.txt)

### Screenshots

![fsScreen_2024_12_24_12_06_44](https://github.com/user-attachments/assets/309036af-63b2-4f0b-a328-330253f6cbf8)
![fsScreen_2024_12_24_12_10_42](https://github.com/user-attachments/assets/5fc101c0-fa89-4f5b-8a51-311c3fef0d91)
![fsScreen_2024_12_24_12_10_52](https://github.com/user-attachments/assets/edeb6206-7daa-4061-b61f-494c51119c64)

**Comment by Resandise** [comment]
Still not Returning to Start Point in 8.0.0.2
![fsScreen_2024_12_27_19_55_26](https://github.com/user-attachments/assets/518d94b7-1d79-41e8-83e2-b607c11e999e)
![fsScreen_2024_12_27_19_55_37](https://github.com/user-attachments/assets/1be53ed6-3ecc-4dd6-82c8-16557e604565)

[log.txt](https://github.com/user-attachments/files/18264656/log.txt)

**Comment by pvaiko** [comment]
It returns the the starting point only, if the work starts on the headland. Your course seems to start in the center and end on the headland, in this case there is no return by design.

**Comment by Resandise** [comment]
@pvaiko @Tensuko 


I did a course with Headland first, and it still did not return to starting point

[Uploading log.txt…]()
![fsScreen_2024_12_28_10_04_10](https://github.com/user-attachments/assets/79f90e79-e07c-44f3-ad45-e3e5f860747c)
![fsScreen_2024_12_28_10_04_21](https://github.com/user-attachments/assets/51120e43-7023-4866-bb24-d2ba0f0d1c88)

**Comment by Tensuko** [comment]
Load 8.0.0.3 first and they try again.
Had a problem with pathfinder, should be fixed now.

**Comment by Resandise** [comment]
@Tensuko I will when it releases, thanks

**Comment by Tensuko** [comment]
![grafik](https://github.com/user-attachments/assets/992299b2-31c2-44e5-ac2d-f105194cd967)

**Comment by Resandise** [comment]
I notice, front page still shows 8.0.0.2 as newest release
