### ISSUE TITLE
Missed Corner

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS25#94]
### Version

8.0.0.1

### Game Version

1.4.0.0

### SP/MP

SP (Singleplayer)

### What happened?

While cultivating field, CP missed driver did a round turn on corner, but course is a sharp corner. Started on center, and then when it transitioned to headland, it drove off field to the short edge, made a pass and did a round turn to the long edge.  

### How can we reproduce this?

Create course on field 4 of River Bends map, starting on center.  

### What did you expect to happen?

CP to make a sharp corner

### Attach your log.txt!

[log.txt](https://github.com/user-attachments/files/18241380/log.txt)

### Screenshots

![fsScreen_2024_12_24_12_06_22](https://github.com/user-attachments/assets/ef711a0f-fab9-4daa-b7dd-6a18f8bed357)
![fsScreen_2024_12_24_12_10_42](https://github.com/user-attachments/assets/6671767a-5ca7-4f17-aff5-b8039febf285)
![fsScreen_2024_12_24_12_10_42](https://github.com/user-attachments/assets/aa25182a-e111-40fa-b6c8-4d2f0fa2812b)

**Comment by Resandise** [comment]
It also miss the NW corner on Field 3 prior to running Field 4.

**Comment by Resandise** [comment]
![fsScreen_2024_12_24_12_27_47](https://github.com/user-attachments/assets/5325af32-f1fe-45c5-8d7a-31da1cc115ad)
[log.txt](https://github.com/user-attachments/files/18241427/log.txt)
Screenshot and log for missed corner on Field 5

**Comment by Tensuko** [comment]
Might be fixed in the next Release

**Comment by pvaiko** [comment]
Yes, should be fixed by https://github.com/Courseplay/Courseplay_FS25/pull/102
