### ISSUE TITLE
Option for Center to generate on Long Side of Field

### ISSUE THREAD

**Issue by Resandise** [Courseplay/Courseplay_FS25#95]
### Version

8.0.0.1

### SP/MP

SP (Singleplayer)

### What can be done with your idea?

Add an option to generate center Direction of Rows to Manual/Auto/Long Edge

### If applicable, how would the user interface look like for this enhancement?

Add another button in the Direction of Rows for Long Edge

### Is there an alternative?

maybe

### Screenshots

![fsScreen_2024_12_24_12_33_46](https://github.com/user-attachments/assets/e2a8edae-29bf-42e3-a965-6ecd9992cb15)

**Comment by Tensuko** [comment]
Sorry but that option was removed.
The auto setting should detect the best longest lines already, if not there is still the manual option.
