### ISSUE TITLE
CP Custom Fields

### ISSUE THREAD

**Issue by davcor57** [Courseplay/Courseplay_FS25#97]
### Version

8.0.0.1

### SP/MP

SP (Singleplayer)

### What is your question about?

more later

### What is your question?

How do you delete or rename custom fields?

### Screenshots

![fsScreen_2024_12_24_15_03_13](https://github.com/user-attachments/assets/63b28288-a95a-449f-a3ee-8a3208d0e3e6)

**Comment by Tensuko** [comment]
In the folder in modSettings.
Edit and delete comes later as written in the changelog.
