### ISSUE TITLE
Vorgewende auf Bahnen im Uhrzeigersinn

### ISSUE THREAD

**Issue by MrSengy** [Courseplay/Courseplay_FS25#98]
Hallo liebes Courseplay Team, 

Uns ist im MP aufgefallen das die Bahnenberechnung im Uhrzeigersinn Probleme macht, wenn er vom Vorgewende auf die Bahnen wechseln soll. Beim mähen fährt er ab dem Punkt gerade aus als wenn ihm die Verbindung fehlt. Gegen den Uhrzeigersinn funktioniert es.

**Comment by Tensuko** [comment]
Template nutzen!
